### ISSUE TITLE
How can we indicate the user of the transcoding progress?

### ISSUE THREAD

**Issue by razwasserstein** [jbavari/cordova-plugin-video-editor#10]
Is there an event, or some indication to the transcoding progress? So we can show the user some feedback / indication of the process?

Thanks,
Doron

**Comment by oliverholmberg** [comment]
Before you call VideoEditor.transcodeVideo, you could load a spinner or another indication of the transcoding being in progress, then remove the spinner indicator in your success call back function.

For long transcodes, you might consider notifying the user that the process has started, and let them continue to use the app, then alert them again on the success call back.

It would be cool to have a percentage based progress indication that could used in the UI to show users progress, though.

**Comment by rossmartin** [comment]
A `progress` callback was added for android in v1.0.2 and for iOS in v1.0.3
