### ISSUE TITLE
thumbnail creation not working

### ISSUE THREAD

**Issue by sdjoyson** [jbavari/cordova-plugin-video-editor#101]
Help me to get video thumbnail from device local storage.

var videoTranscodeSuccess = function(result) {
    // result is the path to the transcoded video on the device
    myApp.alert('videoTranscodeSuccess, result: ' + result);
  // result = /storage/emulated/0/Movies/toons/3434343.mp4

  VideoEditor.createThumbnail(
      createThumbnailSuccess,
      createThumbnailError,
      {
        fileUri: 'file://'+result,
        outputFileName:'randomString1',
        atTime: 2, // optional, location in the video to create the thumbnail (in seconds)
        // width: 320, // optional, width of the thumbnail
        // height: 480, // optional, height of the thumbnail
        quality: 60 // optional, quality of the thumbnail (between 1 and 100)
      }
    );
  }
 var createThumbnailSuccess = function(result) {
    // result is the path to the jpeg image on the device
    myApp.alert('createThumbnailSuccess, result:'+ result);

```
var file = '/' + result;

localStorage.setItem('videoThumbnail', file);
myApp.alert(file);
```

}

**Comment by sdjoyson** [comment]
video thumbnail display , but takes 10 sec.
var createThumbnailSuccess = function(result) {

 myApp.modal({
                              afterText: '<div style="width: auto; margin:5px -15px -15px">'+                             
                               '<img src="'+result+'" height="150" style="display:block">' +                                
                              '</div>'+
                            '</div>'});
}

**Comment by DevStarlight** [comment]
I think you got an error in this line `fileUri: 'file://'+result,`. When you transcode a video, the response already gives you the new path where you can find the file and you don't have to use `file://`

**Comment by DevStarlight** [comment]
Try changing `fileUri: 'file://'+result` for `file:/' + result`

**Comment by sdjoyson** [comment]
sorry for the late . yes you are correct , thanks .i ve copied the sample code for get videothumbnail and upload.
/* var captureSuccess = function(mediaFiles) {
  var file = mediaFiles[0].fullPath; */

VideoEditor.createThumbnail(
        createThumbnailSuccess,
        createThumbnailError,
        {
          fileUri: file,
          outputFileName: imagefileName,
          maintainAspectRatio: false,
          atTime: 2, 
          width: 320,
          height: 480,
          quality: 100
        }
      );
  var createThumbnailSuccess = function(result) {
    // result is the path to the jpeg image on the device 
          window.localStorage.setItem('thumbnail', result);
           var options = new FileUploadOptions();
            options.fileKey="file"; 
            options.fileName=result.substr(result.lastIndexOf('/')+1); 
            options.mimeType="image/jpeg"; 
            var params = new Object();
            params.value = window.localStorage.getItem('key');
            options.params = params;
            // options.fileName = name;
            options.chunkedMode = true;           
            
 
            var ft = new FileTransfer();
             ft.upload(result, encodeURI("http://**********/thumbupload.php"), win, fail, options);
