### ISSUE TITLE
File not Found but ... file exists

### ISSUE THREAD

**Issue by CostanzoPablo** [jbavari/cordova-plugin-video-editor#11]
Cordova + platform Android

Line Code: 
fileUri: currentEntries[file].fullPath

Error:
java.net.MalformedURLException: Protocol not found: /mt4p/VID_20150208_175451753.mp4

________________________________________________________
Edit Code:
fileUri: 'file://' + currentEntries[file].fullPath

Error:
java.io.FileNotFoundException

The file exist and doing console.log(currentEntries[file].fullPath); it says /mt4p/VID_20150208_175451753.mp4

Full code:

function getFileSystem(){
    window.requestFileSystem(LocalFileSystem.PERSISTENT, 0,
        function(fileSystem){ // success get file system
            root = fileSystem.root;
            listDir(root);
        }, function(evt){ // error get file system
            console.log("File System Error: "+evt.target.error.code);
        }
    );
}

function listDir(directoryEntry){
    $('#files').empty();
    $('#files').append('<div class="back" onclick="goBack();">BACK</div>');
    if( !directoryEntry.isDirectory ) console.log('listDir incorrect type');    

    currentDir = directoryEntry; // set current directory
    directoryEntry.getParent(function(par){ // success get parent
        parentDir = par; // set parent directory
        if( (parentDir.name == 'sdcard' && currentDir.name != 'sdcard') || parentDir.name != 'sdcard' ) $('#backBtn').show();
    }, function(error){ // error get parent
        console.log('Get parent error: '+error.code);
    });
    
    var directoryReader = directoryEntry.createReader();
    directoryReader.readEntries(function(entries){
        currentEntries = entries;
        for(var i=0; i<entries.length; ++i){ // show directories
            //var entry = sortedArr[i];
            //var blockLetter = uiBlock[i%4];
            //console.log(entry.name);
            if( entries[i].isDirectory ){
                $('#files').append('<div class="folder" onclick="openFolder('+ i + ');">' + entries[i].name + '</div>');
            }else{
                $('#files').append('<div class="file" onclick="openFile('+ i + ');">' + entries[i].name + '</div>');
            }
                
        }

    }, function(error){
        console.log('listDir readEntries error: '+error.code);
    });
}

function openFolder(folder){
    currentDir.getDirectory(currentEntries[folder].name, {create:false},
        function(dir){ // success find directory
            listDir(dir);
        }, 
        function(error){ // error find directory
            console.log('Unable to find directory: '+error.code);
        }
    );
}

function openFile(file){
    console.log(currentEntries[file].fullPath);
    VideoEditor.transcodeVideo(
        videoSuccess, // success cb
        videoError, // error cb
        {
            fileUri: 'file://' + currentEntries[file].fullPath, // the path to the video on the device
            outputFileName: 'file://mt4p/pepito.mp4', // the file name for the transcoded video
            quality: VideoEditorOptions.Quality.MEDIUM_QUALITY,
            outputFileType: VideoEditorOptions.OutputFileType.MPEG4,
            optimizeForNetworkUse: VideoEditorOptions.OptimizeForNetworkUse.YES,
            duration: 20 // optional, specify duration in seconds from start of video
        }
    );
}

AndroidManifest.xml
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.RECORD_VIDEO" />

cordova plugins list
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.videoeditor 0.0.2 "VideoEditor"

**Comment by CostanzoPablo** [comment]
My mistake. Putting this stop giving this error.

fileUri: 'file://mnt/sdcard/1/1.mp4',

Now I have this other: "an error ocurred during transcoding"

**Comment by CostanzoPablo** [comment]
My mistake. outputFileName: 'gg.mp4',
Only name, no path. Like the comment. // the file name for the transcoded video

**Comment by razwasserstein** [comment]
Hi!

Happened to me too..
If I use the resolveLocalFileSystemURI, it returns: "an error ocurred during transcoding".
And if I use the fullPath it returns: "java.net.MalformedURLException: Protocol not found:"..

What can I do?

Android 4.2.2.

**Comment by CostanzoPablo** [comment]
No you got to use the resolveLocalFileSystemURI. Just put ...

The fullPath for the origin
fileURI: 'file: //mnt/sdcard/123456.mp4'

And only the name of the output (without fulPath)
OutputFileName 'gg.mp4'

**Comment by drunkwarg** [comment]
instructions unclear. Please enlighten me and put some  working code here.

what is the correct path for a file? //mnt/sdcard/123456.mp4' is not clear.

I am using ionic and I have a file at file:///android_asset/www/img/smp12.mp4. And another one in the devices sd card root directory.

I tried many options but all of them returned file not found exception. Can you elloborate the your file path solution.
