### ISSUE TITLE
Green row of pixels appears on the border of the video after resize

### ISSUE THREAD

**Issue by maxpaj** [jbavari/cordova-plugin-video-editor#131]
First off: thanks for a great plugin man! 👍 

Second:

I'm seeing an issue where the processed video comes out with a green row of pixels on the right hand side after being shrunk from a larger resolution to a smaller. Here is an example configuration object:

```
{
    fileUri: fileUri,
    outputFileName: this.getRandomID(),
    outputFileType: this.videoEditor.OutputFileType.MPEG4,
    optimizeForNetworkUse: this.videoEditor.OptimizeForNetworkUse.NO,
    width: 1920
}
```

I thought about this a little and figured that the following could happen:

The recorded video is some odd resolution, like 2568x1440 or something. Then when shrinking the video to 1920xH, the height (H) could amount to some number that is not an integer, lets say 1080.4. The .4 extra pixels would then ceil the resolution to 1081. But the original video doesn't contain any data for that last row of pixels, so it doesn't entirely cover the green background of the video. (0, 0, 0) in YUV colorspace results in green.

Does that make any sense?

**Comment by maxpaj** [comment]
Edited the title and description.

**Comment by krij0n** [comment]
@maxpaj did you find a solution? Having the same issue..

**Comment by maxpaj** [comment]
Yeah. The issue is that when you scale it, you have to make sure that the scaling doesn't cause calculate the new width or height to a fraction. Both width and height need to be integers. 

Having that said... Looking at my code which I wrote some time back, I'm unsure how this solves it:

```
this.videoEditor.getVideoInfo({ fileUri: videoFilePath }).then((videoInfo) => {
    let editorOptions: any = {
        fileUri: videoFilePath,
        outputFileName: this.getRandomID(),
        outputFileType: this.videoEditor.OutputFileType.MPEG4,
        optimizeForNetworkUse: this.videoEditor.OptimizeForNetworkUse.NO
    };
    
    if(this.platform.is('ios')) {
        editorOptions.width = 1280
    } else {
        editorOptions.height = videoInfo.orientation === 'landscape' ? 720 : 1280;
    }

    this.videoEditor.transcodeVideo(editorOptions).then((newVideoPath: string) => {

    });
});
```

**Comment by JianhuisHuang** [comment]
> Yeah. The issue is that when you scale it, you have to make sure that the scaling doesn't cause calculate the new width or height to a fraction. Both width and height need to be integers.
> 
> Having that said... Looking at my code which I wrote some time back, I'm unsure how this solves it:
> 
> ```
> this.videoEditor.getVideoInfo({ fileUri: videoFilePath }).then((videoInfo) => {
>     let editorOptions: any = {
>         fileUri: videoFilePath,
>         outputFileName: this.getRandomID(),
>         outputFileType: this.videoEditor.OutputFileType.MPEG4,
>         optimizeForNetworkUse: this.videoEditor.OptimizeForNetworkUse.NO
>     };
>     
>     if(this.platform.is('ios')) {
>         editorOptions.width = 1280
>     } else {
>         editorOptions.height = videoInfo.orientation === 'landscape' ? 720 : 1280;
>     }
> 
>     this.videoEditor.transcodeVideo(editorOptions).then((newVideoPath: string) => {
> 
>     });
> });
> ```
@maxpaj Hi, I have the same issue and I follow your code but not work for me, and you have find a solution? thx.

**Comment by maxpaj** [comment]
I think the solution was making sure that the new calculated size does not come out to be a fraction.
