### ISSUE TITLE
Create thumbnail function give only one frame on Android.

### ISSUE THREAD

**Issue by bolotkalil** [jbavari/cordova-plugin-video-editor#145]
Hello, Guys.

I'm trying create thumbnails from a video, with createThumbnail  function. But it gives only one thumbnail when i'm creating 21 snapshots by specific time with loop.
On iOS it works fine. But on Android it doesn't work.
Whats wrong in Android version of createThumbnail?

Many thanks, for your help.

**Comment by Juanperezc** [comment]
HI can you show me that code? i am doing the same on IOS

**Comment by bolotkalil** [comment]
Hi, @Juanperezc .
I use recursive call like this:
`
$scope.getSnapshots = function(index){			
			VideoEditor.createThumbnail(
				function(result){		
					$scope.snapshots.push(result);
					$scope.getSnapshots(++index);
				},
				function(error){
					$modal.alert('Oops something went wrong, please try again.');
				},
				{
					fileUri: $scope.videoPath,
					outputFileName: $scope.getRandomString(), 
					atTime: $scope.snapshotSteps[index].time,
					quality: 90, 
					width: 240,
					height: 320,
				}
			);	
		}`

**Comment by Juanperezc** [comment]
Hello, I already solved I'm using angular 4(ionic), it was a problem in the options
