### ISSUE TITLE
Transcoding not working in Jelly Bean

### ISSUE THREAD

**Issue by karvapallo** [jbavari/cordova-plugin-video-editor#15]
An app using the VideoEditor was working just fine before I updated to Lollipop (or rather CM12 on the OnePlus One). Then it suddenly started giving me a very vague warning about the video transcoding just failing. Is this a known issue and can someone please confirm if they can get this working on Lollipop (or CM12?) Thank you.

Edit: For some reason I had originally reported this as a problem affecting Jelly Bean, but what I meant was Lollipop (Android 5.X)

**Comment by razwasserstein** [comment]
Hi,

I think you are right! We haven't tested it ourselves, but some of our users (with Note 3, Android 4.3) have reported problem transcoding videos.

Please look into it.
Doron

**Comment by razwasserstein** [comment]
Hi,
After doing a bit more testing, I am not sure the problem is with Android 4.3. It might be related to Galaxy Note 3. @karvapallo, did it happen to you on Note 3? Or another device?

Thanks,
Doron

**Comment by karvapallo** [comment]
@razwasserstein actually I'm using OnePlus One and I completely misreported the Android version. I meant Lollipop, not Jelly Bean, or more precisely the CM12 on the OnePlus One. My apologies for the incorrect report.

**Comment by rossmartin** [comment]
@razwasserstein @karvapallo 

I believe your issue is due to the licensing on ffmpeg4android library.

Please check out the PR (https://github.com/jbavari/cordova-plugin-video-editor/pull/13) I mention in this https://github.com/jbavari/cordova-plugin-video-editor/issues/20 I think this will fix your issues.

**Comment by karvapallo** [comment]
@rossmartin thanks for the infor, I'll check it out and see if that helps!

**Comment by cldcloud** [comment]
Hello.
I have the same problem: on my Lolipop devise (Nexus 5) I can't concatenate vodeos and megre it with their own audios. While concateating, I have a this line in the LogCat:
"sxCon> error: only position independent executables (PIE) are supported."
My target SDK is 22, my min SDK is 16, so, what should i do to prevent this error?

**Comment by rossmartin** [comment]
The original issue with this was caused by the licensing on the ffmpeg4android library.  This was fiixed by https://github.com/jbavari/cordova-plugin-video-editor/commit/c348dc19a8165e639488be3fcdf6884b62ea4fe7

@cldcloud you may want to open a new issue for yours.
