### ISSUE TITLE
trim start point

### ISSUE THREAD

**Issue by alanquigley** [jbavari/cordova-plugin-video-editor#16]
Is it possible to set a trim start point with the plugin?

**Comment by rossmartin** [comment]
Not yet but I plan on adding that.  Will update this when it is added.

Thanks.

**Comment by alanquigley** [comment]
Hi Ross, we added already on our fork. We've also added server other functions such as frame sequences.

**Comment by srinivasulurao** [comment]
@alanquigley  can i have the code or any documentation for start time /End time functionality.

**Comment by alanquigley** [comment]
https://github.com/shotclip-team/cordova-plugin-video-editor/network

**Comment by srinivasulurao** [comment]
@alanquigley  thanks a lot, what parameter do i need to pass for start time ?

**Comment by alanquigley** [comment]
execVideoEditor('trim', videoID, {
      inputFile       : inputID,
      outputFileName  : output,
      trimStart       : 1,
      trimEnd         : 5
    })

Should be something like that, very much tailored to work with our internal
data model, but you should be able to glean from the code the correct
approach.

**Comment by srinivasulurao** [comment]
@alanquigley  awesome, i have one last question with this, can we assign the quality option as well, just like we had in the jbavari plugin.

**Comment by alanquigley** [comment]
Not sure, try it :)

**Comment by rossmartin** [comment]
@alanquigley Thank you for the additions on the plugin.  I added the trim functionality your team created for the ios/android version.

@srinivasulurao 

You can now trim a video in the latest version (0.0.6) of the plugin -

https://github.com/jbavari/cordova-plugin-video-editor/tree/0.0.6#trim-a-video

**Comment by srinivasulurao** [comment]
@rossmartin iam getting an error, **trim: failed to trim video**, the transcoding was working nicely but not the trim, can u please help me for this.

**Comment by srinivasulurao** [comment]
@rossmartin  seems like the execFFMPEG function is not trimming the video, can u please help me out for this quickly, i have told my client already that the the trimming is working.

**Comment by rossmartin** [comment]
@srinivasulurao Are you testing on real android device or emulator?

Does the shotclip-team fork work for you?  I am using their exact same code they added for trimming but the `inputFile` parameter is `fileUri`.  Trim is working for me on my Galaxy S2 on 4.2.2

**Comment by srinivasulurao** [comment]
@rossmartin  i am using a real android device,i somehow made it working, i found that that the file path extension is coming as something like this ** ".document/data/data" ** it should come as **".mp4"** or any other format, Secondly we should  use the external sd card path for the storage of the video after trimming, just like you did in the transcoding which was perfectly coded, right now it is storing in a cache folder.

Also is there any way to load the video from sdcard and get its duration, in my case the video.duration is giving a null value, any help would be appreciated :)

**Comment by manikandan-b** [comment]
@rossmartin i used your video editor plugin and try to trim a video and i am getting error pop up as "index=0;index=1"  please give me support ASAP it will be appreciated.
