### ISSUE TITLE
Project license statement?

### ISSUE THREAD

**Issue by brodybits** [jbavari/cordova-plugin-video-editor#18]
Thanks @jbavari and @rossmartin for putting this plugin together! A simple license statement would help people who want to reuse your project, MIT and/or Apache 2 would be most preferred.

**Comment by kmturley** [comment]
This library also relies on another library ffmpeg4android, which requires a license:

    I/Videokit﹕ licenseCheck in path: /data/data/com.example.hello/files
    I/Videokit﹕ isLicExistsComplex...
    I/Videokit﹕ trying to open /data/data/com.example.hello/files/ffmpeglicense.lic
    I/Videokit﹕ license file found...
    I/Videokit﹕ You used 1 of your 15 trial days.

I believe this is the license information here:
http://www.appfree.org/item.php?item_id=com.netcompss.ffmpeg4android
http://ffmpeg4android.netcompss.com/home/purchase

**Comment by rossmartin** [comment]
@kmturley 

I found this out awhile back and there is a pull request from April 2 (#13) that has not been merged yet. I refactored the android plugin to use [android-ffmpeg-java](https://github.com/guardianproject/android-ffmpeg-java) (which is actually better anyways and is free) and this pull request is ready to go fixing this issue.

Thanks.

**Comment by brodybits** [comment]
Thanks guys, but my original question is if we can get a license statement about this project itself?

Apache 2.0 (and/or MIT) would be preferred since it is more commercial-friendly and would encourage wider reuse. GPL would cause problems for many users. Even LGPL can cause problems for iOS users, as described here: http://blog.burhum.com/post/38236943467/your-lgpl-license-is-completely-destroying-ios

**Comment by brodybits** [comment]
Congratulations, by integrating #13 you have now subjected this project to GPL. Please mark it in README.md that this plugin can only be used in an open-source project with a GPL or AGPL license.

**Comment by brodybits** [comment]
Let me correct myself: I _did_ discover that the Apache 2.0 license is specified in plugin.xml, which is perfect. It would be great to see this stated in a LICENSE file or the README. In addition, it would be great if the Android version can be fixed to use a non-GPL FFMPEG library such as https://github.com/appunite/AndroidFFmpeg

**Comment by jbavari** [comment]
@brodybits We'd love some help maintaining this repo. Can you throw us a PR?

**Comment by brodybits** [comment]
Will do, cannot promise when.

**Comment by kmturley** [comment]
I've noticed a fair few issues with the underlying libraries too. I reported a duration calculation issue and another with trying to deleting input files by default. Also some of the command run are slow or could be optimised for speed.

I also wanted to combine 3 files together and add an overlay, and none of this functionality was supported in the library.

Personally I think this project would benefit by starting from a clean plugin which can run ffmpeg commands directly from javascript. Then we can layer on some helper functions and some default presets to aid others.

Here is the command I am using for my project:

    ./ffmpeg -y -i intro.mp4 -f mpegts -qscale 0 0.ts
    ./ffmpeg -y -i recording.mp4 -i overlay.png -filter_complex "[0:v][1:v] overlay=0:0" -ac 2 -f mpegts -qscale 0 1.ts
    ./ffmpeg -y -i outro.mp4 -f mpegts -qscale 0 2.ts
    ./ffmpeg -y -i "concat:0.ts|1.ts|2.ts" -f mpegts -qscale 0 output.mpg

**Comment by rossmartin** [comment]
@kmturley as of https://github.com/jbavari/cordova-plugin-video-editor/commit/ec59490deea948e94a81d81062909d1c25313b2d you can run ffmpeg commands directly from JavaScript.

I'll be updating the plugin version on npm and tagging soon.

@brodybits We have documented licensing for the plugin.  The Android version is GPL because it includes the android-ffmpeg-java library.  iOS is MIT.

**Comment by kmturley** [comment]
Nice! one thing to note, you may want some security around running ffmpeg using JS. If it can write to files/folders etc Love this feature though!
