### ISSUE TITLE
Build keeps failing

### ISSUE THREAD

**Issue by pixellet14** [jbavari/cordova-plugin-video-editor#183]
The build keeps failing with the following error

`Could not find method compile() for arguments [com.github.ergovia-mobile:android-transcoder:v0.1.10R_ergovia] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

**Comment by TinerfeV** [comment]
Hi, I have the same problem, how did you manage to solve it?

**Comment by pixellet14** [comment]
@TinerfeV hi, I have switched to cordova-plugin-ffmpeg and uninstalled this one. Also, for converting the videos to stream faster I have even installed ffmpeg on my server and use the command in my php file to execute the same.
