### ISSUE TITLE
Reference Error VideoEditor is not defined

### ISSUE THREAD

**Issue by rohitmel** [jbavari/cordova-plugin-video-editor#19]
Hi Guys,
I hope someone could help me with this. I  added the plugin to an existing project via the below command

cordova plugin add https://github.com/jbavari/cordova-plugin-video-editor.git

Plugin got added successfully but when using it based on the documentation, I get an error related to VideoEditor not defined. Not sure if the they I need to include the plugin is wrong or if the way to call the plugin transcode function should be different.

Thanks

PS: we want to be able to create a small video sizes as when a user on Android creates even a small video of 6 seconds the file size is > 10M. So we hope that using this plugin will help to reduce the filesize so it can be transferred over the 3G, 4G connection.

**Comment by kh411d** [comment]
Hi, have u figure this out? I've got the same issue, using cordova 5.2.0

**Comment by rossmartin** [comment]
@kh411d 

This should be fixed in the latest version - https://github.com/jbavari/cordova-plugin-video-editor/tree/0.0.6
