### ISSUE TITLE
concatAndTrimFilesMP4Stream function has error using duration

### ISSUE THREAD

**Issue by kmturley** [jbavari/cordova-plugin-video-editor#21]
When using the concatAndTrimFilesMP4Stream function there is a bug in the code of the convertToMP4Stream function. Here is the original code which outputs 00:00:5.6 - an invalid duration:

    double dValue = mediaIn.duration;
    int hours = (int)(dValue/3600f);
    dValue -= (hours*3600);

    cmd.add("0");
    cmd.add(String.format(Locale.US,"%s",hours));
    cmd.add(":");

    int min = (int)(dValue/60f);
    dValue -= (min*60);

    cmd.add("0");
    cmd.add(String.format(Locale.US,"%s",min));
    cmd.add(":");

    cmd.add(String.format(Locale.US,"%f",dValue));
    //cmd.add("00:00:" + String.format(Locale.US,"%f",mediaIn.duration));

My fixed version outputs 00:00:05

    cmd.add(Double.toString(mediaIn.duration));

However after fixing this, I have another another transcode error which I can't figure out, here is my code for VideoEditor.java:

    FfmpegController ffmpegController = new FfmpegController(appContext, appContext.getCacheDir());
    TranscodeCallback tcCallback = new TranscodeCallback();

    ArrayList<Clip> listVideos = new ArrayList<Clip>();

    Clip clip = new Clip();
    clip.path = new File(videoSrcPath).getCanonicalPath();
    ffmpegController.getInfo(clip);
    clip.duration = 5;
    listVideos.add(clip);

    Clip clip2 = new Clip();
    clip2.path = new File(videoSrcPath2).getCanonicalPath();
    ffmpegController.getInfo(clip2);
    clip2.duration = 5;
    listVideos.add(clip2);

    Clip clipOut = new Clip();
    clipOut.path = new File(outputFilePath).getCanonicalPath();

    ffmpegController.concatAndTrimFilesMP4Stream(listVideos, clipOut, false, false, new ShellUtils.ShellCallback() {
        @Override
        public void shellOut(String shellLine) {
            System.out.println("fc>" + shellLine);
        }
        @Override
        public void processComplete(int exitValue) {
            if (exitValue < 0)
                System.err.println("concat non-zero exit: " + exitValue);
        }
    });

Do you have a working version using the concatAndTrimFilesMP4Stream I could reference?

**Comment by kmturley** [comment]
Ok I have a working version using the following code:

VideoEditor.java line 10

    import org.ffmpeg.android.ShellUtils;

VideoEditor.java line 22

    import org.ffmpeg.android.ShellUtils;

VideoEditor.java line 99

    // intro
    final File inFile = this.resolveLocalFileSystemURI(options.getString("fileUri"));
    if (!inFile.exists()) {
        Log.d(TAG, "input file does not exist");
        callback.error("input video does not exist.");
        return;
    }

    // recording
    final File inFile2 = this.resolveLocalFileSystemURI(options.getString("fileUri2"));
    if (!inFile2.exists()) {
        Log.d(TAG, "input file2 does not exist");
        callback.error("input video2 does not exist.");
        return;
    }

    // outro
    final File inFile3 = this.resolveLocalFileSystemURI(options.getString("fileUri3"));
    if (!inFile3.exists()) {
        Log.d(TAG, "input file3 does not exist");
        callback.error("input video3 does not exist.");
        return;
    }

    // overlay
    final File inFile4 = this.resolveLocalFileSystemURI(options.getString("fileUri4"));
    if (!inFile4.exists()) {
        Log.d(TAG, "input file4 does not exist");
        callback.error("input video4 does not exist.");
        return;
    }

    final String videoSrcPath = inFile.getAbsolutePath();
    final String videoSrcPath2 = inFile2.getAbsolutePath();
    final String videoSrcPath3 = inFile3.getAbsolutePath();
    final String videoSrcPath4 = inFile4.getAbsolutePath();

VideoEditor.java line 250

    FfmpegController ffmpegController = new FfmpegController(appContext, appContext.getCacheDir());
    TranscodeCallback tcCallback = new TranscodeCallback();

    ArrayList<Clip> listVideos = new ArrayList<Clip>();

    Clip clip = new Clip();
    clip.path = new File(videoSrcPath).getCanonicalPath();
    ffmpegController.getInfo(clip);
    clip.duration = 5;
    listVideos.add(clip);

    Clip clip2 = new Clip();
    clip2.path = new File(videoSrcPath2).getCanonicalPath();
    ffmpegController.getInfo(clip2);
    clip2.duration = 5;
    listVideos.add(clip2);

    Clip clip3 = new Clip();
    clip3.path = new File(videoSrcPath3).getCanonicalPath();
    ffmpegController.getInfo(clip3);
    clip3.duration = 5;
    listVideos.add(clip3);

    Clip clipOut = new Clip();
    clipOut.path = new File(outputFilePath).getCanonicalPath();

    ffmpegController.concatAndTrimFilesMP4Stream(listVideos, clipOut, false, false, new ShellUtils.ShellCallback() {
        @Override
        public void shellOut(String shellLine) {
            System.out.println("fc>" + shellLine);
        }
        @Override
        public void processComplete(int exitValue) {
            if (exitValue < 0)
                System.err.println("concat non-zero exit: " + exitValue);
        }
    });

FfmpegController.java line 664

    /*
    double dValue = mediaIn.duration;
    int hours = (int)(dValue/3600f);
    dValue -= (hours*3600);

    cmd.add("0");
    cmd.add(String.format(Locale.US,"%s",hours));
    cmd.add(":");

    int min = (int)(dValue/60f);
    dValue -= (min*60);

    cmd.add("0");
    cmd.add(String.format(Locale.US,"%s",min));
    cmd.add(":");

    cmd.add(String.format(Locale.US,"%f",dValue));
    */
    cmd.add(Double.toString(mediaIn.duration));

You may want to look at the duration issue within the library inside your library :)

**Comment by rossmartin** [comment]
Thanks I will fix this in the android-ffmpeg-java - this functionality isn't currently used in the plugin though.
