### ISSUE TITLE
Example project installation or installation instructions?

### ISSUE THREAD

**Issue by zocheyado** [jbavari/cordova-plugin-video-editor#22]
The plugin looks amazing but I was wondering how exactly to install it and or set it up. I read through the usage instructions but I am trying to figure out exactly where I have to put stuff in order to get this to work, I am currently testing on Ionic so I do not expect someone to have an example of that but and example of the plugin in a cordova project would be amazing!

**Comment by flyakite** [comment]
Try to run this command in your project folder.
cordova plugin add https://github.com/jbavari/cordova-plugin-video-editor.git

**Comment by zocheyado** [comment]
Sorry thats not exactly what I meant, the plugin installation using that command works perfectly I was asking if there was an example of it actually being used on a device. For example take a test-video.mov and split it in half using the plugin so I can figure out how to instantiate it, and use the functions as it pertains to the cordova system.

**Comment by flyakite** [comment]
If you're talking about the usage but not installation, those were already described in the Usage section of this project, from taking a video to trimming and transcoding. Sorry I don't get your point.

**Comment by kh411d** [comment]
I did run "cordova plugin add https://github.com/jbavari/cordova-plugin-video-editor.git"
Got this undefined VideoEditor, it seems not loaded, tried to listen to 'deviceready' but still got undefined VideoEditor, I'm on Cordova 5.2.0 android build

**Comment by web75018** [comment]
hi there. i need to use it with ionic too.
any step by step or how to article?

thanks a lot

**Comment by rossmartin** [comment]
@web75018 

You don't need to include a js file in  your index.html or inject a VideoEditor angular module.  The plugin will make `VideoEditor` and `VideoEditorOptions` global.  The `VideoEditor.js` and `VideoEditorOptions.js` will be automatically added by cordova.

Here is the necessary stuffs in plugin.xml that makes this happen
```xml
<js-module name="VideoEditor" src="www/VideoEditor.js">
    <clobbers target="VideoEditor" />
</js-module>

<js-module name="VideoEditorOptions" src="www/VideoEditorOptions.js">
    <clobbers target="VideoEditorOptions" />
</js-module>
```

I am not sure that this plugin can work with PhoneGap Build.  I use this plugin in my Ionic app, works fast in iOS but slow in Android because it uses ffmpeg.

**Comment by web75018** [comment]
Thanks a lot for reply!!!
i try to use it inside ionic project too.
will try to update the plugin.xml file and feedback.



2015-11-04 2:02 GMT+01:00 Ross Martin <notifications@github.com>:

> @web75018 <https://github.com/web75018>
>
> You don't need to include a js file in your index.html or inject a
> VideoEditor angular module. The plugin will make VideoEditor and
> VideoEditorOptions global. The VideoEditor.js and VideoEditorOptions.js
> will be automatically added by cordova.
>
> Here is the necessary stuffs in plugin.xml that makes this happen
>
> <js-module name="VideoEditor" src="www/VideoEditor.js">
>     <clobbers target="VideoEditor" />
> </js-module>
>
> <js-module name="VideoEditorOptions" src="www/VideoEditorOptions.js">
>     <clobbers target="VideoEditorOptions" />
> </js-module>
>
> I am not sure that this plugin can work with PhoneGap Build. I use this
> plugin in my Ionic app, works fast in iOS but slow in Android because it
> uses ffmpeg.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jbavari/cordova-plugin-video-editor/issues/22#issuecomment-153537906>
> .
>



-- 
Abid

**Comment by srinivasulurao** [comment]
@rossmartin  this plugin is not working, when i tried through the console, its showing me the error "Can't access or make Movies directory", can u please please please help me on this context.

**Comment by rossmartin** [comment]
This should be fixed by https://github.com/jbavari/cordova-plugin-video-editor/commit/ab2bc260886eb75eb82238f1b4b96e0f63e9091f

**Comment by ABr751** [comment]
the trim option is not working
