### ISSUE TITLE
Input files are remove by default after encoding

### ISSUE THREAD

**Issue by kmturley** [jbavari/cordova-plugin-video-editor#23]
This one through me off because I thought I was doing something wrong my end. It turns out this line of code is causing an unexpected behaviour:

VideoEditor.java
line 275 - 278

    if (!inFile.delete()) {
        Log.d(TAG, "unable to delete in file");
    }

After commenting out this line, input files are kept after rendering! Maybe you should consider this action being the default, and users need to pass an option to have the file removed?

**Comment by rossmartin** [comment]
Thanks I went ahead and added a `deleteInputFile` option for android.  It defaults to false and is optional.
