### ISSUE TITLE
Error generating manifest, icon value also present in...

### ISSUE THREAD

**Issue by bluego78** [jbavari/cordova-plugin-video-editor#24]
Hi, sorry but i'm new in plugins, i can't understand how can i add this plugin to my ionic project, if i build my app with build.phonegap.com.
Is this possibile? What i have to do?
Help me please :)

**Comment by bluego78** [comment]
When i try to include this plugin in my project, the build operation exit with this error:

attribute application@icon value=(@drawable/icon) from AndroidManifest.xml is also present at android.org.apache.cordova.videoeditor:andoird-ffmpeg-java:unspecified:debug ......

someone could help me?

This is my config.xml on phonegap application:

<code>
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget id="********" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" xmlns:tools="http://schemas.android.com/tools">
    <name>*****</name>
    <description>****** Application</description>
    <author email="******@gmail.com" href="http://www.****.com">PhoneGap Team</author>
    <content src="index.html" />

    <preference name="permissions" value="none" />
    <preference name="orientation" value="portrait" />
    <preference name="AllowInlineMediaPlayback" value="true"/>
    <preference name="target-device" value="universal" />
    <preference name="fullscreen" value="true" />
    <preference name="webviewbounce" value="true" />
    <preference name="prerendered-icon" value="true" />
    <preference name="stay-in-webview" value="false" />
    <preference name="ios-statusbarstyle" value="black-opaque" />
    <preference name="detect-data-types" value="true" />
    <preference name="exit-on-suspend" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="show-splash-screen-spinner" value="true" />
    <preference name="auto-hide-splash-screen" value="false" />
    <preference name="disable-cursor" value="false" />
    <preference name="android-minSdkVersion" value="14" />
    <preference name="android-installLocation" value="auto" />
    <preference name="KeyboardDisplayRequiresUserAction" value="false" />
    
    <gap:plugin name="org.apache.cordova.battery-status" />
    <gap:plugin name="org.apache.cordova.camera" />
    <gap:plugin name="org.apache.cordova.media-capture" />
    <gap:plugin name="org.apache.cordova.console" />
    <gap:plugin name="org.apache.cordova.contacts" />
    <gap:plugin name="org.apache.cordova.device" />
    <gap:plugin name="org.apache.cordova.device-motion" />
    <gap:plugin name="org.apache.cordova.device-orientation" />
    <gap:plugin name="org.apache.cordova.dialogs" />
    <gap:plugin name="org.apache.cordova.file" />
    <gap:plugin name="org.apache.cordova.file-transfer" />
    <gap:plugin name="org.apache.cordova.geolocation" />
    <gap:plugin name="org.apache.cordova.globalization" />
    <gap:plugin name="org.apache.cordova.inappbrowser" />
    <gap:plugin name="org.apache.cordova.media" />
    <gap:plugin name="org.apache.cordova.network-information" />
    <gap:plugin name="org.apache.cordova.splashscreen" />
    <gap:plugin name="org.apache.cordova.vibration" />
    <gap:plugin name="org.apache.cordova.videoeditor" />

	
	
	
	
	
   <icon src="resources/icon.png" />
	
   <feature name="Keyboard"><param name="ios-package" value="IonicKeyboard" onload="true" /></feature>

	
    <icon gap:platform="android" gap:qualifier="ldpi" src="resources/android/icon/icon-36-ldpi.png" />
    <icon gap:platform="android" gap:qualifier="mdpi" src="resources/android/icon/android/icon-48-mdpi.png" />
    <icon gap:platform="android" gap:qualifier="hdpi" src="resources/android/icon/android/icon-72-hdpi.png" />
    <icon gap:platform="android" gap:qualifier="xhdpi" src="resources/android/icon/android/icon-96-xhdpi.png" />

    
	 
    <icon gap:platform="ios" height="57" src="resources/ios/icon/icon-60.png" width="57" />
    <icon gap:platform="ios" height="72" src="resources/ios/icon/icon-72.png" width="72" />
    <icon gap:platform="ios" height="114" src="resources/ios/icon/icon-60-2x.png" width="114" />
    <icon gap:platform="ios" height="144" src="resources/ios/icon/icon-72-2x.png" width="144" />
    <icon gap:platform="webos" src="resources/ios/icon/webos/icon-64.png" />
    
	
    <gap:splash gap:platform="android" gap:qualifier="port-ldpi" src="resources/android/splash/screen-ldpi-portrait.png" />
    <gap:splash gap:platform="android" gap:qualifier="port-mdpi" src="resources/android/splash/screen-mdpi-portrait.png" />
    <gap:splash gap:platform="android" gap:qualifier="port-hdpi" src="resources/android/splash/screen-hdpi-portrait.png" />
    <gap:splash gap:platform="android" gap:qualifier="port-xhdpi" src="resources/android/splash/screen-xhdpi-portrait.png" />
    <gap:splash gap:platform="android" gap:qualifier="port-xxhdpi" src="resources/android/splash/screen-xxhdpi-portrait.png" />
    <gap:splash gap:platform="android" gap:qualifier="port-xxxhdpi" src="resources/android/splash/screen-xxxhdpi-portrait.png" />
	
    
    <gap:splash gap:platform="ios" height="480" src="resources/ios/splash/screen-iphone-portrait.png" width="320" />
    <gap:splash gap:platform="ios" height="960" src="resources/ios/splash/screen-iphone-portrait-2x.png" width="640" />
    <gap:splash gap:platform="ios" height="1136" src="resources/ios/splash/screen-iphone-portrait-568h-2x.png" width="640" />
    <gap:splash gap:platform="ios" height="1024" src="resources/ios/splash/screen-ipad-portrait.png" width="768" />

	
	
    <access origin="*" subdomains="true"/>
    <plugin name="cordova-plugin-whitelist" version="1" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
</widget>

</code>

**Comment by shahin8r** [comment]
Same problem here when compiling.

```
:mergeDebugResources /platforms/android/build/intermediates/exploded-aar/android.org.apache.cordova.videoeditor/appname-android-ffmpeg-java/unspecified/debug/res/drawable-mdpi-v4/ic_action_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/platforms/android/build/intermediates/exploded-aar/android.org.apache.cordova.videoeditor/appname-android-ffmpeg-java/unspecified/debug/res/drawable-hdpi-v4/ic_action_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/platforms/android/build/intermediates/exploded-aar/android.org.apache.cordova.videoeditor/appname-android-ffmpeg-java/unspecified/debug/res/drawable-xhdpi-v4/ic_action_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

:processDebugManifest/platforms/android/AndroidManifest.xml:7:53 Error:
	Attribute application@icon value=(@drawable/icon) from AndroidManifest.xml:7:53
	is also present at android.org.apache.cordova.videoeditor:appname-android-ffmpeg-java:unspecified:debug:12:9 value=(@drawable/ic_launcher)
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:7:5 to override
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@drawable/icon) from AndroidManifest.xml:7:53
  	is also present at android.org.apache.cordova.videoeditor:appname-android-ffmpeg-java:unspecified:debug:12:9 value=(@drawable/ic_launcher)
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:7:5 to override

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by shahin8r** [comment]
Workaround:

Add `xmlns:tools="http://schemas.android.com/tools"` to your manifest tag in `AndroidManifest.xml` and ` tools:replace="android:icon"` in your application tag.

This works for me.
