### ISSUE TITLE
Extra .mov file remains in Documents directory (iOS)

### ISSUE THREAD

**Issue by danharper** [jbavari/cordova-plugin-video-editor#25]
On iOS, an extra `.mov` file remains in the `Documents` directory following a recording.

Looks to be the [`tempVideoPath` file](https://github.com/jbavari/cordova-plugin-video-editor/blob/c348dc19a8165e639488be3fcdf6884b62ea4fe7/src/ios/VideoEditor.m#L95) created, which is never removed.

**Comment by rossmartin** [comment]
Plan to tackle this one soon.  Thanks.

**Comment by rossmartin** [comment]
This is fixed via f593a6b2c68cae3a02e1fcd155d23a2925a4df4f (v1.0.3)
