### ISSUE TITLE
is trimming working any android version?

### ISSUE THREAD

**Issue by manpreet-logiciel** [jbavari/cordova-plugin-video-editor#27]
Actually, i want to trim video in my app so is trimming working in any android version...

**Comment by rossmartin** [comment]
This has been fixed in commit https://github.com/jbavari/cordova-plugin-video-editor/commit/e9b89a2e4b72d010da6b7eba45b1018ab30ee0dd.

I plan on adding ability to specify trim start/end eventually.

**Comment by srinivasulurao** [comment]
@rossmartin  you are a rock star bro, thank u very much :+1:

**Comment by srinivasulurao** [comment]
@rossmartin  so the trimming based on start time and end time is done or will it take time?

**Comment by manpreet-logiciel** [comment]
@rossmartin when u r planing to add ability to specify trim start and end ...or are u done with that?

**Comment by rossmartin** [comment]
@srinivasulurao @manpreet-logiciel See this here - https://github.com/jbavari/cordova-plugin-video-editor/issues/16#issuecomment-155372308
