### ISSUE TITLE
Is there a way to use complex filter with ffmpeg and avfoundation?

### ISSUE THREAD

**Issue by MrBokeh** [jbavari/cordova-plugin-video-editor#29]
Hi there,
Is there a way to use complex filter with ffmpeg and avfoundation, 
I want to merge two videos side by side and add a PNG water mark.

**Comment by cameronws** [comment]
if you have the know how, you can edit your copy of the plugin to handle extra features mentioned in issue #34.

**Comment by rossmartin** [comment]
@MrBokeh @cameronws 

I plan on making special input to `transcodeVideo` for android that can take a raw ffmpeg command.  You can tell ffmpeg whatever you want it to do from JavaScript land this way.

**Comment by cameronws** [comment]
I'm assuming then that the functionality for this would be similar to that shown in this repo? https://github.com/WritingMinds/ffmpeg-android-java

**Comment by rossmartin** [comment]
@cameronws 

Yeah thinking about it now it would probably be best to have it as a separate plugin function that only works for android.  Something like `VideoEditor.execFfmpegCommand` and have a java method that takes one string input parameter.  This would allow a dev full access to ffmpeg from JavaScript and they have all the power of ffmpeg.

**Comment by cameronws** [comment]
@rossmartin I think that would be the best way to go with that.

**Comment by rossmartin** [comment]
@MrBokeh @cameronws 

This is now possible using `execFFMPEG`.  It is in the master branch as of https://github.com/jbavari/cordova-plugin-video-editor/commit/ec59490deea948e94a81d81062909d1c25313b2d.

I'll be tagging and updating the plugin version on npm soon.
