### ISSUE TITLE
ffmpeg-android

### ISSUE THREAD

**Issue by MrBokeh** [jbavari/cordova-plugin-video-editor#30]
What version of the ffmpeg are you using with? is that the latest 2.8?
The one that you referenced with (ffmpeg v0.11.1) is pulled form below:
https://github.com/WritingMinds/ffmpeg-android   (ffmpeg v2.5)

**Comment by rossmartin** [comment]
Current version is n2.4.2 - I'd like to get a newer version of the binary built for android.
