### ISSUE TITLE
createThumbnail Android fixes

### ISSUE THREAD

**Issue by kmturley** [jbavari/cordova-plugin-video-editor#35]
Seems like the createThumbnail function is not working properly on Android. I managed to get a working version using the following code:

VideoEditor.java
line 323

    @SuppressWarnings("unused")
    private void createThumbnail(JSONArray args) throws JSONException, IOException {
        try {
            JSONObject options = args.optJSONObject(0);
            Log.d(TAG, "options: " + options.toString());
            String sourceVideo = options.getString("fileUri");
            String targetImage = options.getString("outputFileName");
            Bitmap thumbnail = ThumbnailUtils.createVideoThumbnail(sourceVideo.substring(7), MediaStore.Images.Thumbnails.MINI_KIND);
            if (thumbnail == null) {
                callback.error("issue with video codec or something else");
            }
            FileOutputStream theOutputStream;
            try {
                File theOutputFile = new File (targetImage.substring(7));
                if (!theOutputFile.exists()) {
                    if (!theOutputFile.createNewFile()) {
                        callback.error("Could not save thumbnail.");
                    }
                }
                if (theOutputFile.canWrite()) {
                    theOutputStream = new FileOutputStream (theOutputFile);
                    if (theOutputStream != null) {
                        thumbnail.compress(CompressFormat.JPEG, 75, theOutputStream);
                    }
                    else {
                        callback.error("Could not save thumbnail; target not writeable");
                    }
                }
            } catch (IOException e) {
                e.printStackTrace();
                callback.error("I/O exception saving thumbnail");
            }
            callback.success(targetImage);        
        } catch (JSONException e) {
            callback.error("JSON Exception");
        }
    }

In the future I would like to grab different frames for the thumbnail. Would be really useful!

**Comment by rossmartin** [comment]
Are you using the latest plugin version?  I did have an issue recently when passing a file URI that doesn't start with `file:/`.  The latest code in the plugin has this fix - 

```
        String fileUri = options.getString("fileUri");
        if (!fileUri.startsWith("file:/")) {
            fileUri = "file:/" + fileUri;
        }

        File inFile = this.resolveLocalFileSystemURI(fileUri);
        if (!inFile.exists()) {
            Log.d(TAG, "input file does not exist");
            callback.error("input video does not exist.");
            return;
        }
        String srcVideoPath = inFile.getAbsolutePath();
```

And then it uses the `srcVideoPath` - 
```
Bitmap thumbnail = ThumbnailUtils.createVideoThumbnail(srcVideoPath, MediaStore.Images.Thumbnails.MINI_KIND);
```

The problem with android is its inconsistencies on file paths.  I'm not sure we can always rely on `substring(7)` with the file paths.  I use the `resolveLocalFileSystemURI` method for this reason - I can't remember which official cordova plugin uses this but it has support for being passed `content:` URIs.

I hear you being able to make a thumbnail for a specific frame in a clip I will certainly add this when I get some time.

Thanks.

**Comment by kmturley** [comment]
Yeah I tried with the latest plugin code before making my own version. I agree substring(7), isn't the best approach, it was a quick solution to get it working. I'll investigate using resolveLocalFileSystemURI instead!

**Comment by kmturley** [comment]
Just another note, whenever you use:

    options.getString("fileUri");

This throws a JSONException if the property doesn't exist. However if you use:

    options.optString("fileUri");

This will return null and continue running. Might be useful to switch them over

**Comment by rossmartin** [comment]
@kmturley Thanks I'll make that change in the next round of updates.

**Comment by rossmartin** [comment]
I haven't seen any other reports on this.  I did update `createThumbnail` and it now supports new options (atTime will let you grab different frames for the thumbnail) - 

https://github.com/jbavari/cordova-plugin-video-editor#create-jpeg-image-from-video
```
VideoEditor.createThumbnail(
    success, // success cb
    error, // error cb
    {
        fileUri: 'file-uri-here', // the path to the video on the device
        outputFileName: 'output-name', // the file name for the JPEG image
        atTime: 2, // optional, location in the video to create the thumbnail (in seconds)
        width: 320, // optional, width of the thumbnail
        height: 480, // optional, height of the thumbnail
        quality: 100 // optional, quality of the thumbnail (between 1 and 100)
    }
)
```

**Comment by kmturley** [comment]
cool, I don't have a device to test right now. But looking forward to trying it out!
