### ISSUE TITLE
Trouble Loading into Ionic Project

### ISSUE THREAD

**Issue by jeffchuber** [jbavari/cordova-plugin-video-editor#36]
I've tried everything, so thought I would post an issue. I install the project with:

`cordova plugin add cordova-plugin-video-editor`

I confirmed that the `plugin.xml` for the plugin matches https://github.com/jbavari/cordova-plugin-video-editor/issues/22.

I run 'ionic serve' - and VideoEditor is undefined. As a couple simple tests, I put 

```html
<script type="text/javascript">
    ionic.Platform.ready(function(){
      console.log('VideoEditor', VideoEditor);
    });
</script>
```

at the bottom of the index.html for the ionic project - but it is still undefined. 

I then thought it might be a browser versus emulator thing, so I add this variable to my main page

```js
$scope.videoed = function() {
  if (typeof(VideoEditor) !== 'undefined') {
      console.log('loaded');
    return 'loaded';
  } else {
    console.log('not loaded');
    return 'not loaded';
  }
};

$scope.videoeditor = $scope.videoed();
```

However - even in the iOS emulator - the value shows "not loaded."

I'm at my wits end! I would appreciate any tips on things to try. More broadly I am attempting to get videos from iOS and Android losslessly - the quality setting on cordova's getPicture does not apply to videos (or at least not in an understandable way) and therefore users are uploading less than full res videos. 

Thank you!

**Comment by rossmartin** [comment]
Are you running the app natively on the iOS simulator or through a mobile browser (Safari)?  

What happens when you run it on a physical device via Xcode or Android Studio?

Thanks.

**Comment by rossmartin** [comment]
Also, have you rebuilt the app since adding the plugin?  `ionic build ios` / `ionic build android`

I think you'll need to rebuild the app after adding the plugin.  `ionic serve` won't have the latest stuff unless another build is done after adding the plugin.

**Comment by jeffchuber** [comment]
Update

`ionic build android` and `ionic build ios` are now both successful. 

However "not loaded" is still happening ionic serve, the iOS emulator in xcode, and when I run to my iPhone via xcode. 

:/ thoughts?

**Comment by rossmartin** [comment]
Can you try removing the plugin and re-adding?

`cordova plugin remove cordova-plugin-video-editor`

`cordova plugin add cordova-plugin-video-editor`

Then do a build and run the app on a physical device.

**Comment by rossmartin** [comment]
Is the code below that you showed being done after `deviceready` ?

```
$scope.videoed = function() {
  if (typeof(VideoEditor) !== 'undefined') {
      console.log('loaded');
    return 'loaded';
  } else {
    console.log('not loaded');
    return 'not loaded';
  }
};

$scope.videoeditor = $scope.videoed();
```

**Comment by jeffchuber** [comment]
It's in my auth.js controller (took out all the non-relevant stuff)
```js
angular.module('scapp.auth', [])
  .controller('LoginCtrl', function(
    $scope,
    $ionicPopup,
    $ionicLoading,
    $ionicModal,
    $state,
    $auth) {

      $scope.logout = function() {
        //logout stuff
      };

      $scope.doLogin = function() {
        //login stuff
      };

    $scope.videoed = function() {
      if (typeof(VideoEditor) !== 'undefined') {
          console.log('loaded');
        return 'loaded';
      } else {
        console.log('not loaded');
        return 'not loaded';
      }
    };

    $scope.videoeditor = $scope.videoed();

});
```

this is the view that I'm sending the text to (took out all the non-relevant stuff)
```html
<ion-view>
  <ion-content>
    <!-- login form -->
    <h1>{{videoeditor}}</h1>
  </ion-content>
</ion-view>
```

much appreciated

**Comment by rossmartin** [comment]
In your `scapp.auth` controller can you do this and tell me what it logs?
```
angular.module('scapp.auth', [])
  .controller('LoginCtrl', function(
    $scope,
    $ionicPopup,
    $ionicLoading,
    $ionicModal
    $ionicPlatform, // inject this
    $state,
    $auth) {

  $ionicPlatform.ready(function() {
    console.log('VideoEditor' + VideoEditor);
    console.log('typeof VideoEditor ' + typeof VideoEditor);
  });

});
```

I think the issue is that your controller is loaded before `deviceready`.

**Comment by jeffchuber** [comment]
Thank you for your help Ross, as it turns out - I had a silent error that the keyboard wasn't loading properly and was preventing downstream `$ionicPlatform.ready` sigh. 

I have another questions, but I will close this - because it is resolved! :boom:
