### ISSUE TITLE
Video compression on iOS with cordova-plugin-camera. can this help?

### ISSUE THREAD

**Issue by jeffchuber** [jbavari/cordova-plugin-video-editor#37]
Cordova's Camera Plugin is compressing my videos on iOS regardless of quality filter. This is what it looks like when I select a video in my app. (that is a prosthesis) 
![screen shot 2015-11-20 at 3 02 16 pm](https://cloud.githubusercontent.com/assets/891664/11314370/dc125858-8f99-11e5-90b3-7d56660c5943.png)

I want users to be able to upload the video's losslessly. I tried sending both FILE_URI and NATIVE_URI to VideoEditor but it errored out as `The requested URL was not found on this server.` (on the iOS emulator)

Is there a way to do this? I've found dozens of other users with the same problem, and it seems it might be a bug in the parent library. Thanks!

**Comment by rossmartin** [comment]
Hey glad to see you figured out the issue with the plugin.  

I haven't looked into this much yet but it looks like the `UIImagePickerController` will always compress a selected video.  This is what the `cordova-plugin-camera` uses so I think you'll have to create your own.

Have you seen this post on stackoverflow? [How to avoid compression after selecting video from UIImagePickerController in ios](http://stackoverflow.com/questions/20190485/how-to-avoid-compression-after-selecting-video-from-uiimagepickercontroller-in-i)

**Comment by jeffchuber** [comment]
I had not seen that! thank you for posting! 

closing issue

**Comment by rossmartin** [comment]
@jeffchuber I made an asset picker plugin for iOS that does not compress your selected video - https://github.com/rossmartin/cordova-plugin-instagram-assets-picker

**Comment by jeffchuber** [comment]
amazing!! awesome work
