### ISSUE TITLE
A plugin in your app does not support the compulsory arm64 (64-bit support) architecture

### ISSUE THREAD

**Issue by LowSociety** [jbavari/cordova-plugin-video-editor#39]
I get this error when including the plugin in my context.xml and trying to build. Seems pretty uncommon and I can't find any solution to it online.

**Comment by rossmartin** [comment]
Did you add the plugin using the cordova CLI or did you add it to your `config.xml` as a feature?

Here is how to install using the CLI -

```
cordova plugin add cordova-plugin-video-editor
```
