### ISSUE TITLE
1080p for MP4 instead of 720p

### ISSUE THREAD

**Issue by MrBokeh** [jbavari/cordova-plugin-video-editor#40]
Is there a way to transcode the videos to 1080p in MP4 with high quality option instead of 720p?

**Comment by rossmartin** [comment]
Yeah you can manually change this [line 57 in VideoEditor.m ](https://github.com/jbavari/cordova-plugin-video-editor/blob/master/src/ios/VideoEditor.m#L57)

from - 
```
presetName = AVAssetExportPresetHighestQuality;
```

to - 
```
presetName = AVAssetExportPreset1920x1080;
```

I think some devices might not support transcoding to 1920x1080 though.

**Comment by MrBokeh** [comment]
Do you know which device won't support it? Or it's iOS version related?

**Comment by rossmartin** [comment]
I'm not sure and Apple isn't clear on this from what I can find.

I plan on making the iOS plugin use this [AVAssetExportSession drop-in replacement with customizable audio&video settings](https://github.com/rs/SDAVAssetExportSession).

Then I can make the interface to `transcodeVideo` have options like this below for both platforms - 

```
VideoEditor.transcodeVideo(success,fail, {
  width: 1920,
  height: 1080,
  fps: 24
});
```

This will get rid of the quality option and allow for more fine tuning by the dev.

**Comment by MrBokeh** [comment]
I have tried the 1080p preset but with no luck, it still compress the 1080p 60fps video that I recorded on my iPhone as 720p for some reason. I guess when you select a video from the library, there's a "compression" going on which exports everything at 720p or below before you can use the video from the library. Therefore, my question is, is there a way to select the uncompressed video as in the raw video from the library instead?

**Comment by rossmartin** [comment]
Yeah the `cordova-plugin-camera` uses `UIImagePickerController` which will always compress a selected video (https://github.com/jbavari/cordova-plugin-video-editor/issues/37).

Here is a post on stackoverflow describing the situation and how to solve it - http://stackoverflow.com/questions/20190485/how-to-avoid-compression-after-selecting-video-from-uiimagepickercontroller-in-i

I'm considering adding a way to get a video from the gallery uncompressed for iOS to the plugin.

**Comment by MrBokeh** [comment]
Yes please! That would be awesome!

**Comment by MrBokeh** [comment]
Can we re-open this as an enhancement?

**Comment by rossmartin** [comment]
I plan on making a different cordova plugin for this that uses https://github.com/guillermomuntaner/GMImagePicker

There is a pull request on the really good cordova image picker plugin that uses this GMImagePicker but I'm not sure if it supports choosing video - https://github.com/wymsee/cordova-imagePicker/pull/84

I'd like to make a cordova plugin for the GMImagePicker that matches its API.

**Comment by MrBokeh** [comment]
Wow thank you!

**Comment by MrBokeh** [comment]
Are you still working on this for video? It would be cool to choose both 4k and 1080p video (iphone 6/6s) for iOS and using your new video compression features!

**Comment by rossmartin** [comment]
Yeah I want to solve this issue but it's certainly not an issue with the video editor plugin.

The root cause of the problem is because the the `cordova-plugin-camera` uses `UIImagePickerController` which will always compress a selected video.  The same thing happens with the `cordova-plugin-media-capture`.

I plan on making a cordova plugin for the GMImagePicker that matches its API.  This will let us get videos from the library without them being compressed.

The other issue is with capturing video on iOS because the same thing happens.  It may make sense to add a capture function to the plugin for iOS so you can capture video and get it without it being compressed to 720p.

**Comment by rossmartin** [comment]
Hey I created created an asset picker plugin for iOS that does not compress your chosen video - https://github.com/rossmartin/cordova-plugin-instagram-assets-picker

**Comment by MrBokeh** [comment]
You are a legend! Thanks heaps!
