### ISSUE TITLE
Compression progress on both platforms 

### ISSUE THREAD

**Issue by MrBokeh** [jbavari/cordova-plugin-video-editor#41]
Is that possible to add compression progress status update for both platforms?

**Comment by rossmartin** [comment]
I know it is certainly possible for Android.  iOS is very fast from my experience are you working with large files on iOS?

**Comment by MrBokeh** [comment]
Yes, at least an hour long or a few GB files.

**Comment by MrBokeh** [comment]
Please at least add this features to Android, Android is like a zillion times slower on both new and dated devices. I guess a progress indicator to gives the user an idea of how long or percentage would be very helpful to the user. Because they won't just shut the app down and assume the app is not working.

**Comment by sannysinghs** [comment]
are there a way to reduce compression time in android . for now it is taking way too long to encode 42Mb video which 19sec . it took nearly one mine even for LOW_QUALITY

**Comment by rossmartin** [comment]
I'm adding this feature for Android, should be done hopefully by this Sunday.

**Comment by sannysinghs** [comment]
Appreciate your effort :+1:

**Comment by rossmartin** [comment]
@sannysinghs @MrBokeh 

This has been added for android in 1.0.2

You can see how to use it here - https://github.com/jbavari/cordova-plugin-video-editor#how-to-use-the-progress-callback-function-currently-android-only

**Comment by MrBokeh** [comment]
@rossmartin Thanks Ross! Here is the sample code from Apple for command line export plus progress update: https://developer.apple.com/library/mac/samplecode/avexporter/Listings/Objective_C_AVFoundationExporter_AVFoundationExporter_m.html#//apple_ref/doc/uid/DTS40011051-Objective_C_AVFoundationExporter_AVFoundationExporter_m-DontLinkElementID_4

**Comment by rossmartin** [comment]
@MrBokeh 

Nice thanks for sharing that.  I'm going to be on vacation starting tomorrow until next weekend.  I may have this ready for iOS in the next week or so.

**Comment by MrBokeh** [comment]
My pleasure!

-- 
Adrian Leung
Sent with Airmail

On 4 January 2016 at 12:22:44 PM, Ross Martin (notifications@github.com) wrote:

@MrBokeh

Nice thanks for sharing that. I'm going to be on vacation starting tomorrow until next weekend. I may have this ready for iOS in the next week or so.

**Comment by rossmartin** [comment]
Added the progress callback feature for iOS in v1.0.3 https://github.com/jbavari/cordova-plugin-video-editor/commit/973b3d3459031d12dc6572e3eba012bcedd20aa2
