### ISSUE TITLE
Video size and duration/length

### ISSUE THREAD

**Issue by MrBokeh** [jbavari/cordova-plugin-video-editor#44]
Is there a way to get the size and duration/length for both uncompressed and compressed/trim videos?

**Comment by rossmartin** [comment]
The `android-ffmpeg-java` has a helper method built in so adding this for android will be easy.  I'm not sure of the difficulty on iOS but I'd like to do this for both platforms.

**Comment by MrBokeh** [comment]
Thanks a million Ross. I am not sure if this would help:
https://developer.apple.com/library/mac/samplecode/avexporter/Listings/Objective_C_AVFoundationExporter_AVFoundationExporter_m.html#//apple_ref/doc/uid/DTS40011051-Objective_C_AVFoundationExporter_AVFoundationExporter_m-DontLinkElementID_4

**Comment by rossmartin** [comment]
This is next on the list of improvements and I plan on making the same `VideoEditor` function call for each platform.

**Comment by rossmartin** [comment]
This is now possible using the `getVideoInfo` function.

https://github.com/jbavari/cordova-plugin-video-editor#get-info-on-a-video-width-height-orientation-duration-size--bitrate
