### ISSUE TITLE
Execute an FFMPEG command not working in Kitkat and above.

### ISSUE THREAD

**Issue by abhijeet-gupta** [jbavari/cordova-plugin-video-editor#45]
I create the PhoneGap app that needs to upload the video after capture. To reduce the video size, I used the Cordova-plugin-video-editor plugin. This plugin is working fine in JellyBean devices but in KitKat and above it not working. It creates the o bytes file in output location only.

Please help me to solve this problem.

**Comment by rossmartin** [comment]
If you are using the `execFFMPEG` function you need to pass `-y` in the cmd array.

You need a `-y` in that ffmpeg command to write to the output file if it already exists.

Example - 
```
var cmd = ['-y', '-i', inputFilePath, '-b:v', '512k', '-s', '640x640', '-r', '24', '-vcodec', 'libx264', '-strict', '-2', outputFilePath];

VideoEditor.execFFMPEG(
    ffmpegSuccess,
    ffmpegError,
    {
        cmd: cmd
    }
);
```

**Comment by Sachchida-Nand-Mishra** [comment]
It is not helpful for me. Please give me any other solution which have the capability to compress the video on every latest android versions after jellybean.

**Comment by abhijeet-gupta** [comment]
Thanks rossmartin for your response.
I used the exact same code for reducing the size of the video, it is working fine in JellyBean devices but in KitKat and above it is not working.

**Comment by rossmartin** [comment]
I've not had any problem using the `transcodeVideo` or `execFFMPEG` on a device running KitKat or on a device running Lollipop.

Do these devices have an external SD card and are they rooted?

**Comment by abhijeet-gupta** [comment]
My JellyBean device(Samsung S3) is rooted and not have any external SD card. But KitKat device(MicroMax Mi Tablet) is not rooted with no SD card.
Does this problem due to non rooted device?

**Comment by rossmartin** [comment]
Both of my devices are rooted and one has an external SD card.  I don't think the android device has to be rooted.  Do you see any helpful logs trying to use the plugin on your KitKat device?

**Comment by abhijeet-gupta** [comment]
While running on Kitkat device, I viewed all logs in the console but there is no error I found. 
Is there any other way to find the error?

**Comment by Sachchida-Nand-Mishra** [comment]
['-y', '-i', inputFilePath, '-b:a', '32k', '-s', ''+window.screen.width +'x'+ window.screen.height, '-r', '24', '-vcodec', 'libx264', '-strict', '-2', outputFilePath]

it's working correctly on every version of android.

**Comment by rossmartin** [comment]
@Sachchida-Nand-Mishra Thank you for your input.  I've not had any issues with any version of android and I don't think it requires root.

**Comment by rossmartin** [comment]
@abhijeet-gupta Have you been able to resolve get this working on your devices?

**Comment by abhijeet-gupta** [comment]
@rossmartin, 
Yes,It is working with @Sachchida-Nand-Mishra  cmd.

**Comment by Mayank1904** [comment]
2019-10-11 13:33:32.381 27421-27556/com.examples.ffmpeg4android_demo E/linker: "/data/app/com.examples.ffmpeg4android_demo-ILsoGQ8dzOOkQlKmWSaK6Q==/lib/arm/libvideokit.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
2019-10-11 13:33:32.382 27421-27556/com.examples.ffmpeg4android_demo A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 27556 (AsyncTask #3), pid 27421 (eg4android_demo)
