### ISSUE TITLE
Video Bitrate, Video FPS, Video dimension and Audio Channels on iOS

### ISSUE THREAD

**Issue by MrBokeh** [jbavari/cordova-plugin-video-editor#47]
Since we can control all video Bitrate, video FPS, video dimension and audio channels on Android, is there a way to control them on iOS? Because I want to keep the consistency of the output video between iOS and Android.

**Comment by rossmartin** [comment]
I plan on making the iOS plugin use this AVAssetExportSession drop-in replacement with customizable audio&video settings.

Then I can make the interface to transcodeVideo have options like this below for both platforms -

```
VideoEditor.transcodeVideo(success, fail, {
  width: 1920,
  height: 1080,
  fps: 24,
  audioChannels: 2
 .....
});
```
This will get rid of the quality option and allow for more fine tuning by the dev.

**Comment by MrBokeh** [comment]
That would be awesomely awesome!

**Comment by rossmartin** [comment]
This is up on there on the list.  I feel that first there needs to be a way to get the current width/height on a video so you can know what lower resolution you would like to use (without losing the aspect ratio and stretching it).

I'm wanting to make a `VideoEditor` function that works the same on all platforms that returns the following video info - 

- width
- height
- duration
- size
- mimeType / extension

**Comment by bertho-zero** [comment]
The below code :

```
var cmd = ['-i', inputFilePath, '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams'];

VideoEditor.execFFPROBE(
    ffmpegSuccess,
    ffmpegError,
    {
        cmd: cmd,
        progress: function(info) {
            console.log(info);
        }
    }
);

function ffmpegSuccess(result) {
    console.log('execFFMPEG success');
}

function ffmpegError(err) {
    console.log('ffmpegError, err: ' + err);
}
```

echo 

```
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "1/180000",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 1920,
            "height": 1080,
            "coded_width": 1920,
            "coded_height": 1088,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 40,
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "30000/1001",
            "avg_frame_rate": "900000/30019",
            "time_base": "1/90000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 180114,
            "duration": "2.001267",
            "bit_rate": "16077085",
            "bits_per_raw_sample": "8",
            "nb_frames": "60",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0
            },
            "tags": {
                "creation_time": "2016-02-08 03:14:19",
                "language": "eng",
                "handler_name": "VideoHandle"
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "mp4a",
            "codec_tag": "0x6134706d",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/48000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 97930,
            "duration": "2.040208",
            "bit_rate": "156364",
            "max_bit_rate": "96000",
            "nb_frames": "95",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0
            },
            "tags": {
                "creation_time": "2016-02-08 03:14:19",
                "language": "eng",
                "handler_name": "SoundHandle"
            }
        }
    ],
    "format": {
        "filename": "/storage/emulated/0/DCIM/100ANDRO/MOV_0591.mp4",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "2.027000",
        "size": "4095746",
        "bit_rate": "16164759",
        "probe_score": 100,
        "tags": {
            "major_brand": "mp42",
            "minor_version": "0",
            "compatible_brands": "isommp42",
            "creation_time": "2016-02-08 03:14:19",
            "location": "+48.8160+002.3633/",
            "location-eng": "+48.8160+002.3633/"
        }
    }
}
```

**Comment by ballenjr** [comment]
TO: https://github.com/jbavari/cordova-plugin-video-editor/issues/47#issuecomment-181180369

In HTML5 browser I have been able to determine the dimensions of the video from a single frame pull pretty quick. Worst case scenario you could do the same in JS side of the Plugin. But I am sure a similar technique could be fairly easy on iOS. I am just not too savvy with it. I am more heavy on the java side.

I will post an example in a bit...

**Comment by ballenjr** [comment]
Just attach source, wait for signal to play, pause on playing event, set init on pause, if enough data has not yet been read, and play again, then when all data is available use it. My implementation is a little different because of what I am doing but this should work. If not let me know I'll post something verified.

```
vSource.bind("canplaythrough", function() {
    setTimeout(function(){
        vSource.play();
    }, 20);
});

vSource.bind("playing", function() {
    setTimeout(function(){
        vSource.pause();
    }, 20);
});

vSource.bind("durationchange pause", function() {
    if (!this.videoWidth)
        setTimeout(function(){
            vSource.context.play();
        }, 20);
    else
        console.debug("Ready: ", this.videoWidth, this.videoHeight);
});
```

**Comment by ballenjr** [comment]
If that is too hacky for ya, would you be willing to post your "AVAssetExportSession" code to a branch? I am already using this hack to get dimensions for another purpose so I have no issues with using it to inform this as well and I really need this with scaling... Rotation/OrientationChange would be nice too... Maybe?

Honestly I am all for grepping the metadata for real though. I could really use the orientation value on iOS. Right now I have to assume that the user is NOT holding the phone upside down based on the aspect ratio. While I am sure its better than vegas odds I would still rather have the real value. And I have yet to find a way to extract it without ffmpeg.

**Comment by ballenjr** [comment]
I like your idea of the ```maintainAspectRatio``` option. What do you think of having a small list of phone dimension limiters too? And/Or maybe a ```limitDimToDevice``` kind of option?

With the latter if set to true(defaults to false) then the dimensions are auto limited to the native screen. Maybe with a upscale factor to keep some extra pixels... I did it with images. It seems to work pretty well.

The list of phone configs could also include frame rates and any other option that could be deemed as appropriately optimizing.

**Comment by ballenjr** [comment]
Would this also allow cropping as suggested here?: https://github.com/jbavari/cordova-plugin-video-editor/issues/38#issuecomment-169963454

**Comment by rossmartin** [comment]
@ballenjr There will be a new version out later today with an updated `transcodeVideo` for both platforms that will support new options - 

```
 * width            - width for the output video
 * height           - height for the output video
 * videoBitrate     - video bitrate for the output video in bits
 * audioChannels    - number of audio channels for the output video
 * audioSampleRate  - sample rate for the audio (samples per second)
 * audioBitrate     - audio bitrate for the output video in bits
```

The new code for `transcodeVideo` is already in master but I am going to be adding another function for both platforms today that allows you to get the width, height, duration, size, and bitrate (maybe more).

**Comment by ballenjr** [comment]
Sweet! This is going to be awesome.

I posted another question that I don't know if it will get visibility since I put it on a closed thread here: https://github.com/jbavari/cordova-plugin-video-editor/issues/57#issuecomment-183874377

**Comment by ballenjr** [comment]
I took a look at the code in master. It looks like the answer to the question I had about cropping is no it won't be possible. Is that right? If so is it even possible using these tools? I have never tried it with ffmpeg but I can see how it could be useful for some cases to be able select one dimension to clip for outputting a new aspect ratio.

**Comment by rossmartin** [comment]
@ballenjr I am going to add a `maintainAspectRatio` option as well to `transcodeVideo`.  Working on that at the moment.

**Comment by rossmartin** [comment]
This is now available in version 1.0.6 

https://github.com/jbavari/cordova-plugin-video-editor#transcode-a-video

Please note that the `quality` option is no longer available or needed.

**Comment by MrBokeh** [comment]
Thanks Ross!

**Comment by ballenjr** [comment]
You rock man, can't wait to try it.
