### ISSUE TITLE
crop the thumbnail

### ISSUE THREAD

**Issue by MrBokeh** [jbavari/cordova-plugin-video-editor#48]
Is there a way to crop the thumbnail to a specific size? as well as control the jpeg compression settings? (e.g. export the jpeg thumbnail as 300 width x 50 height with 65% compression)

**Comment by rossmartin** [comment]
Not currently on either platform.

**Comment by MrBokeh** [comment]
Is that possible to add this into the plugin?
http://stackoverflow.com/questions/612131/whats-the-easiest-way-to-resize-optimize-an-image-size-with-the-iphone-sdk
I guess UIImageJPEGRepresentation set with 1.0 will result with a vary large "thumbnail". Plus it will be a good idea if i can resize it to a smaller size and a lower compression like 50% of the width and height and 50% compression etc.

**Comment by rossmartin** [comment]
I have started working on this for iOS, should be done in the next few days.  Not sure when I'll get it done for Android.

The options will be - 
```
VideoEditor.createThumbnail(
    createThumbnailSuccess,
    createThumbnailError,
    {
        fileUri: videoUri,
        outputFileName: videoFileName,
        atTime: 2, // where at in the video to create the jpeg (in seconds)
        width: 480,
        height: 640,
        quality: 100 // int between 1 and 100
    }
);
```

**Comment by rossmartin** [comment]
createThumbnail has been updated on both platforms to support the options shown above - d781dab

Here is the updated doc for it - https://github.com/jbavari/cordova-plugin-video-editor#create-jpeg-image-from-video
