### ISSUE TITLE
Android video rotated 90

### ISSUE THREAD

**Issue by J-who** [jbavari/cordova-plugin-video-editor#54]
Why are android videos being rotated 90 degrees after using ````transcodeVideo````? My landscape videos are now in portrait and vice versa. I am using ````$cordovaCapture.captureVideo```` and the video appears correctly, and then after a render it's then been rotated.

**Comment by rossmartin** [comment]
Thanks for reporting this.  I have seen this issue before.  Can you modify the plugin code in your project locally?  If so you can comment out lines 338 to 341 here in the file below -

https://github.com/jbavari/cordova-plugin-video-editor/blob/master/src/android/android-ffmpeg-java/src/org/ffmpeg/android/FfmpegController.java#L336

From the root of your cordova project it should be located at `platforms/android/cordova-plugin-video-editor/${project}-android-ffmpeg-java/src/org/ffmpeg/android/FfmpegController.java`

**Comment by J-who** [comment]
That did the trick, thanks! I know with the ```$cordovaCapture.captureVideo``` I had to set ```correctOrientation: true``` in order to get my landscape video orientation set properly on Android.
