### ISSUE TITLE
Android Thumbnails do not match video ratio

### ISSUE THREAD

**Issue by J-who** [jbavari/cordova-plugin-video-editor#55]
Is it possible to have the thumbnail generator to match the same ratio as the video? Thumbnails for Landscape videos are turned into squares and look horrible.

**Comment by rossmartin** [comment]
I'll look into it.  I haven't touched any of the thumbnail code for either platform since I originally wrote it.

**Comment by rossmartin** [comment]
I'm working on this for iOS currently as well as some other improvements.  I'll be focusing on android next when I'm done.

The new createThumbnail will have more options (atTime, width, height, and quality) - 

```
VideoEditor.createThumbnail(
    createThumbnailSuccess,
    createThumbnailError,
    {
        fileUri: videoUri,
        outputFileName: videoFileName,
        atTime: 2, // where at in the video to create the jpeg (in seconds)
        width: 480,
        height: 640,
        quality: 100 // int between 1 and 100
    }
);
```

On iOS it is  relatively easy to get the image to keep the same aspect ratio as the source when resizing.  I haven't looked into android yet but I would think it is possible.

**Comment by MrBokeh** [comment]
Thanks matey, you are a legend!

**Comment by rossmartin** [comment]
@J-who @MrBokeh 

`createThumbnail` has been updated on both platforms to support the options shown above - d781dabf65b7362c00646e9cd10d10bcb062c329

Here is the updated doc for it - https://github.com/jbavari/cordova-plugin-video-editor#create-jpeg-image-from-video

**Comment by J-who** [comment]
Thank you for all the updates so far!

The ```createThumbnail``` seems to work perfectly, except for videos on the Android being pulled from the video library.

video filepath: ```content://media/external/video/media/12661```
success callback: ```java.io.FileNotFoundException```

Minor side issue:
I've also noticed that if you try to create a thumbnail from the ```transcodeVideo``` result, it will always come out square, but if you created it from the ```$cordovaCapture.captureVideo```, youll get the correct ratio. Not sure if this is intended?

**Comment by rossmartin** [comment]
Thanks for letting me know about the videos pulled from the video library.  This is just android being inconsistent between OS versions and I'll have to figure out a way to support nearly all of the kinds of file URIs you can get back from the cordova camera plugin.

About the dimensions - this is intended.   The reason you get a square thumbnail from the transcoded videos is because their aspect ratio is square.  https://github.com/jbavari/cordova-plugin-video-editor#a-note-on-width-and-height-used-by-createthumbnail

I can make it so that you can always get a square thumbnail but they will likely come out stretched and lose the aspect ratio.

**Comment by J-who** [comment]
Should it be throwing an error instead of saying it was successful?

I'm using the thumbnails for the poster for ```<video>``` blocks. I'll just make sure I'm creating a thumbnail from the original capture.

**Comment by rossmartin** [comment]
I'm surprised it makes it to the success callback.  You can make a new issue for this - 

> The createThumbnail seems to work perfectly, except for videos on the Android being pulled from the video library.
> 
> video filepath: content://media/external/video/media/12661
> success callback: java.io.FileNotFoundException

I'll see what I can do about the videos from the gallery on this next update.

**Comment by ballenjr** [comment]
FOR: https://github.com/jbavari/cordova-plugin-video-editor/issues/55#issuecomment-182650660

This may help, https://github.com/cdibened/filechooser

There are a few forks with some extra commits too that I have not checked out yet. I am going to though cuz I am hopeful that one of them has that one key feature that never got implemented and maybe a more current support for newer versions of cordova with all that goodness.

It works with kitkat and seems to provide consistency with more modern versions. It did not work as well with jellybean for me. But I don't support jellybean anymore.
