### ISSUE TITLE
FFmpeg stream input/output support

### ISSUE THREAD

**Issue by bertho-zero** [jbavari/cordova-plugin-video-editor#56]
Hey,

Would it be possible to add FFmpeg stream input/output support ?

For example, for download and convert a video in same time, it's a conversion on-the-fly.

**Comment by rossmartin** [comment]
Whatever ffmpeg can do, you can make happen with the execFFMPEG command -https://github.com/jbavari/cordova-plugin-video-editor#execute-an-ffmpeg-command-android-only

Do you know what the ffmpeg command(s) are that are needed.

**Comment by bertho-zero** [comment]
Thanks,

I have already seen that but i was asking myself if this plugin work with streams (input and output), for example : 

> ffmpeg -i pipe:0 -f avi -c:v libxvid -vtag XVID pipe:1

usually used as :

> python __main__.py 'https://www.youtube.com/watch?v=4bPGxLxogvw' -f best -o - | ffmpeg -i pipe:0 -f avi -c:v libxvid -vtag XVID pipe:1 | cat > test.avi

**Comment by rossmartin** [comment]
Ah interesting - I think what you can do is create an output file and then write the output to it.  I'll have to look into some of the ffmpeg-android-java examples to see but I think it is possible.

I think where you have the `| cat > test.avi` you will need to supply an absolute path on the android filesystem and then the filename you want.

**Comment by rossmartin** [comment]
Oh and this guy was able to get an RTSP stream working - https://github.com/jbavari/cordova-plugin-video-editor/issues/43

I think this will work for you just supply an absolute file path on the android filesystem for the output.

**Comment by bertho-zero** [comment]
In this example it is `| cat > test.avi` but otherwise there are other treatment behind.

**Comment by bertho-zero** [comment]
And then I struggled to integrate other libraries in ffmpeg, I will persevere.

**Comment by rossmartin** [comment]
Added via PR #58.  Documentation for `execFFPROBE` will be added soon.
