### ISSUE TITLE
Update ffmpeg to the latest version

### ISSUE THREAD

**Issue by bertho-zero** [jbavari/cordova-plugin-video-editor#57]
Hi,

I created a [repository for easy update ffmpeg](https://github.com/bertho-zero/ffmpeg-android) to the latest version (actually n2.5.11, the n2.4.2 is 16 month old), I added the below libaries to ffmpeg : libmp3lame, fdk-aac, opus, ogg and verbis.

This build configuration also generate a ffprobe binary, if you want.

https://github.com/bertho-zero/ffmpeg-android

**Comment by rossmartin** [comment]
Awesome I'll get the latest binary integrated into the project soon.  Came down with mono last Tuesday been moving pretty slow 😑

**Comment by rossmartin** [comment]
Hey I can't compile the binaries on my macbook using that repo or the original.  I don't have Linux installed on my HTPC but I could put another drive in it and do it on there probably.  

Another thought is could you build an android ffmpeg binary and provide the binary somehow?

Here is another possible solution maybe (fmpeg-android script, modified to run on Mac.) - https://github.com/falnatsheh/ffmpeg-android

**Comment by bertho-zero** [comment]
I havn't Mac for test and compile, sorry.
Can you report your error here ?

I will immediately create a release archive containing the last ffmpeg + ffprobe binaries.

**Comment by bertho-zero** [comment]
You can retry, I copied the only difference that I found.

**Comment by rossmartin** [comment]
I can give it another try but I don't think it will compile on OS X.  I installed all dependencies and android ndk, no luck.

See this issue here from the official repo, they say it is not possible to build on OS X - 
https://github.com/WritingMinds/ffmpeg-android/issues/9

**Comment by bertho-zero** [comment]
It's a shame, tamps ..

I shared a build.zip which contains ffmpeg and ffprobe compiled for Android 3 architectures, privilege armeabi-v7a, and I did a pull request that includes the method execFFPROBE on cordova module

ps: Sorry for my bad English, it's not my native language, i'm French.

**Comment by rossmartin** [comment]
Thanks and don't worry about the English.

**Comment by rossmartin** [comment]
Thanks for your PR and the new updated binaries.  When I get some time I'll test out the `execFFPROBE` and add it to the docs.  It is currently in the new version (1.0.5) but I haven't added documentation for it yet.

**Comment by ballenjr** [comment]
I see from the controller that x264 is included. I also see that the ultrafast option is added... 

I am by no means and ffmpeg guru but I do recall reading somewhere that HW Acceleration is a compile option. But when I was researching compiling ffmpeg for android I got the impression that there were too many chipsets to practically implement this. Is/Was this a mitigating factor when compiling these binaries? Is gpu access not feasible/available at this time?
