### ISSUE TITLE
transcodeVideo error in version 1.0.6

### ISSUE THREAD

**Issue by glauconsantana** [jbavari/cordova-plugin-video-editor#64]
On Android, transcodeVideo with maintainAspectRatio = true generates the mp4 file, but corrupted.
With maintainAspectRatio = false works fine, but I need maintainAspectRatio.

Sorry my poor english.

Android 4.4.2 and 5.0.2
Cordova 5.4.0, 5.4.1 and 6.0

log:
D/VideoEditor( 5308): shellOut: ffmpeg version N-78332-g14bf59c Copyright (c) 2000-2016 the FFmpeg developers
D/VideoEditor( 5308): shellOut:   built with gcc 4.8 (GCC)
D/VideoEditor( 5308): shellOut:   configuration: --target-os=linux --cross-prefix=/var/www/html/ffmpeg-android/toolchain-android/bin/arm-linux-androideabi- --arch=arm --cpu=cortex-a8 --enable-runtime-cpudetect --sysroot=/var/www/html/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-libass --enable-libfreetype --enable-libfribidi --enable-fontconfig --enable-libmp3lame --enable-libfdk-aac --enable-libopus --enable-libvorbis --enable-gpl --enable-nonfree --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --enable-ffprobe --enable-gpl --enable-yasm --disable-doc --disable-shared --enable-static --pkg-config=/var/www/html/ffmpeg-android/ffmpeg-pkg-config --prefix=/var/www/html/ffmpeg-android/build/armeabi-v7a --extra-cflags='-I/var/www/html/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all' --extra-ldflags='-L/var/www/html/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-libs='-lpng -lexpat -lm' --extra-cxxflags=
D/VideoEditor( 5308): shellOut:   libavutil      55. 17.100 / 55. 17.100
D/VideoEditor( 5308): shellOut:   libavcodec     57. 24.101 / 57. 24.101
D/VideoEditor( 5308): shellOut:   libavformat    57. 24.101 / 57. 24.101
D/VideoEditor( 5308): shellOut:   libavdevice    57.  0.101 / 57.  0.101
D/VideoEditor( 5308): shellOut:   libavfilter     6. 28.100 /  6. 28.100
D/VideoEditor( 5308): shellOut:   libswscale      4.  0.100 /  4.  0.100
D/VideoEditor( 5308): shellOut:   libswresample   2.  0.101 /  2.  0.101
D/VideoEditor( 5308): shellOut:   libpostproc    54.  0.100 / 54.  0.100
I/MediaStoreImporter( 6037): Update: incremental Added music: 0 Updated music: 0 Deleted music: 0 Created playlists: 0 Updated playlists: 0 Deleted playlists: 0 Inserted playlist items: 0 Deleted playlist items: 0 Removed orphaned playlist items: 0
D/MusicLifecycle( 6037): com.google.android.music.wear.WearBroadcastReceiver generated event: Broadcast received with context android.app.ReceiverRestrictedContext@26814d32 and intent Intent { act=com.google.android.music.IMPORT_COMPLETE flg=0x10 cmp=com.google.android.music/.wear.WearBroadcastReceiver }
D/ActivityManager(  805): startService callerProcessName:com.google.android.music, calleePkgName: com.google.android.music
D/ActivityManager(  805): retrieveServiceLocked(): component = com.google.android.music/com.google.android.music.wear.WearMetadataSyncService; callingUser = 0; userId(target) = 0
D/ActivityManager(  805): caller:android.app.ApplicationThreadProxy@39fe89cd, r.packageName :com.google.android.music
D/VideoEditor( 5308): shellOut: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/DCIM/Camera/20160217_095633.mp4':
D/VideoEditor( 5308): shellOut:   Metadata:
D/VideoEditor( 5308): shellOut:     major_brand     : mp42
D/VideoEditor( 5308): shellOut:     minor_version   : 0
D/VideoEditor( 5308): shellOut:     compatible_brands: isommp42
D/VideoEditor( 5308): shellOut:     creation_time   : 2016-02-17 11:56:37
D/VideoEditor( 5308): shellOut:   Duration: 00:00:03.33, start: 0.000000, bitrate: 3366 kb/s
D/VideoEditor( 5308): shellOut:     Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 640x480, 3115 kb/s, 23.83 fps, 24 tbr, 90k tbn, 180k tbc (default)
D/VideoEditor( 5308): shellOut:     Metadata:
D/VideoEditor( 5308): shellOut:       rotate          : 270
D/VideoEditor( 5308): shellOut:       creation_time   : 2016-02-17 11:56:37
D/VideoEditor( 5308): shellOut:       handler_name    : VideoHandle
D/VideoEditor( 5308): shellOut:     Side data:
D/VideoEditor( 5308): shellOut:       displaymatrix: rotation of 90.00 degrees
D/VideoEditor( 5308): shellOut:     Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
D/VideoEditor( 5308): shellOut:     Metadata:
D/MusicLifecycle( 6037): com.google.android.music.store.MediaStoreImportService generated event: Service destroyed
D/VideoEditor( 5308): shellOut:       creation_time   : 2016-02-17 11:56:37
D/VideoEditor( 5308): shellOut:       handler_name    : SoundHandle
D/MusicLifecycle( 6037): com.google.android.music.wear.WearMetadataSyncService generated event: Service created
D/ActivityManager(  805): retrieveServiceLocked(): component = null; callingUser = 0; userId(target) = 0
D/MusicLifecycle( 6037): com.google.android.music.wear.WearMetadataSyncService generated event: Service started with intent Intent { cmp=com.google.android.music/.wear.WearMetadataSyncService }
D/WearableService(21868): callingUid 10007, callindPid: 21868
E/GmsUtils( 6037): Failed to connect to Google API client: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
E/GmsUtils( 6037): Failed to connect to Google API client: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
D/MusicLifecycle( 6037): com.google.android.music.wear.WearMetadataSyncService generated event: Service destroyed
I/ActivityManager(  805): Killing 5451:com.google.android.partnersetup/u0a10 (adj 15): empty #25
D/VideoEditor( 5308): shellOut: [libx264 @ 0xb946e950] height not divisible by 2 (320x427)
D/VideoEditor( 5308): shellOut: Output #0, mp4, to '/storage/emulated/0/Android/data/br.com.suporteinfor.apptome/cache/VID_video.mp4':
D/VideoEditor( 5308): shellOut:   Metadata:
D/VideoEditor( 5308): shellOut:     major_brand     : mp42
D/VideoEditor( 5308): shellOut:     minor_version   : 0
D/VideoEditor( 5308): shellOut:     compatible_brands: isommp42
D/VideoEditor( 5308): shellOut:     Stream #0:0(eng): Video: h264, none, q=2-31, 128 kb/s, 24 fps (default)
D/VideoEditor( 5308): shellOut:     Metadata:
D/VideoEditor( 5308): shellOut:       handler_name    : VideoHandle
D/VideoEditor( 5308): shellOut:       creation_time   : 2016-02-17 11:56:37
D/VideoEditor( 5308): shellOut:       encoder         : Lavc57.24.101 libx264
D/VideoEditor( 5308): shellOut:     Stream #0:1(eng): Audio: aac, 0 channels, 128 kb/s (default)
D/VideoEditor( 5308): shellOut:     Metadata:
D/VideoEditor( 5308): shellOut:       creation_time   : 2016-02-17 11:56:37
D/VideoEditor( 5308): shellOut:       handler_name    : SoundHandle
D/VideoEditor( 5308): shellOut:       encoder         : Lavc57.24.101 aac
D/VideoEditor( 5308): shellOut: Stream mapping:
D/VideoEditor( 5308): shellOut:   Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
D/VideoEditor( 5308): shellOut:   Stream #0:1 -> #0:1 (aac (native) -> aac (native))
D/VideoEditor( 5308): shellOut: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
D/VideoEditor( 5308): ffmpeg finished
D/VideoEditor( 5308): execute method starting
D/VideoEditor( 5308): createThumbnail firing
D/VideoEditor( 5308): options: {"fileUri":"\/storage\/emulated\/0\/Android\/data\/br.com.suporteinfor.apptome\/cache\/VID_video.mp4","outputFileName":"thumbVideo","atTime":1,"quality":80}
E/Vold    (  237): Failed to find mounted volume for /storage/extSdCard/Android/data/br.com.suporteinfor.apptome/cache/
W/Vold    (  237): Returning OperationFailed - no handler for errno 0
W/ContextImpl( 5308): Failed to ensure directory: /storage/extSdCard/Android/data/br.com.suporteinfor.apptome/cache
E/wpa_supplicant( 1494): IAPP SNAP_HDR Mismatch
E/wpa_supplicant( 1494): IAPP SNAP_HDR Mismatch
D/VideoEditor( 5308): shellOut: /data/data/br.com.suporteinfor.apptome/app_bin/ffmpeg -y -ss 1 -i /storage/emulated/0/Android/data/br.com.suporteinfor.apptome/cache/VID_video.mp4 -vframes 1 -q:v 5 /storage/emulated/0/Android/data/br.com.suporteinfor.apptome/cache/PIC_thumbVideo.jpg 
D/VideoEditor( 5308): shellOut: ffmpeg version N-78332-g14bf59c Copyright (c) 2000-2016 the FFmpeg developers
D/VideoEditor( 5308): shellOut:   built with gcc 4.8 (GCC)
D/VideoEditor( 5308): shellOut:   configuration: --target-os=linux --cross-prefix=/var/www/html/ffmpeg-android/toolchain-android/bin/arm-linux-androideabi- --arch=arm --cpu=cortex-a8 --enable-runtime-cpudetect --sysroot=/var/www/html/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-libass --enable-libfreetype --enable-libfribidi --enable-fontconfig --enable-libmp3lame --enable-libfdk-aac --enable-libopus --enable-libvorbis --enable-gpl --enable-nonfree --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --enable-ffprobe --enable-gpl --enable-yasm --disable-doc --disable-shared --enable-static --pkg-config=/var/www/html/ffmpeg-android/ffmpeg-pkg-config --prefix=/var/www/html/ffmpeg-android/build/armeabi-v7a --extra-cflags='-I/var/www/html/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all' --extra-ldflags='-L/var/www/html/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-libs='-lpng -lexpat -lm' --extra-cxxflags=
D/VideoEditor( 5308): shellOut:   libavutil      55. 17.100 / 55. 17.100
D/VideoEditor( 5308): shellOut:   libavcodec     57. 24.101 / 57. 24.101
D/VideoEditor( 5308): shellOut:   libavformat    57. 24.101 / 57. 24.101
D/VideoEditor( 5308): shellOut:   libavdevice    57.  0.101 / 57.  0.101
D/VideoEditor( 5308): shellOut:   libavfilter     6. 28.100 /  6. 28.100
D/VideoEditor( 5308): shellOut:   libswscale      4.  0.100 /  4.  0.100
D/VideoEditor( 5308): shellOut:   libswresample   2.  0.101 /  2.  0.101
D/VideoEditor( 5308): shellOut:   libpostproc    54.  0.100 / 54.  0.100
D/VideoEditor( 5308): shellOut: [mov,mp4,m4a,3gp,3g2,mj2 @ 0xb921f1a0] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
D/VideoEditor( 5308): shellOut: [mov,mp4,m4a,3gp,3g2,mj2 @ 0xb921f1a0] moov atom not found
D/VideoEditor( 5308): shellOut: /storage/emulated/0/Android/data/br.com.suporteinfor.apptome/cache/VID_video.mp4: Invalid data found when processing input
D/VideoEditor( 5308): processComplete: 1
D/VideoEditor( 5308): ffmpeg finished
D/VideoEditor( 5308): execute method starting
D/VideoEditor( 5308): getVideoInfo firing
D/VideoEditor( 5308): options: {"fileUri":"file:\/storage\/emulated\/0\/Android\/data\/br.com.suporteinfor.apptome\/cache\/VID_video.mp4"}
D/VideoEditor( 5308): videoSrcPath: /storage/emulated/0/Android/data/br.com.suporteinfor.apptome/cache/VID_video.mp4
V/MediaPlayerService(  259): Create new media retriever from pid 5308
E/MetadataRetrieverClient(  259): offset (0) bigger than file size (0)
E/PluginManager( 5308): Uncaught exception from plugin
E/PluginManager( 5308): java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA

**Comment by rossmartin** [comment]
What options are you passing to `transcodeVideo`?  What version of android are you using?

I can see that you are passing this to `createThumbnail` - 

```
{
  "fileUri":"\/storage\/emulated\/0\/Android\/data\/br.com.suporteinfor.apptome\/cache\/VID_video.mp4",
  "outputFileName":"thumbVideo",
  "atTime":1,
  "quality":80
}
```

I have a suspicion that the `MediaMetadataRetriever` is causing an issue in `transcodeVideo`.

**Comment by glauconsantana** [comment]
fileUri: videoData[0].fullPath, //$cordovaCapture.captureVideo result
                                    outputFileName: timestamp + "_video",
                                    maintainAspectRatio: true,
                                    width: 320,
                                    height: 320,
                                    outputFileType: VideoEditorOptions.OutputFileType.MPEG4,
                                    optimizeForNetworkUse: VideoEditorOptions.OptimizeForNetworkUse.YES,
                                    saveToLibrary: false

**Comment by rossmartin** [comment]
Hmmm this is odd, it looks like the ffmpeg scale is calculating the height incorrect.

`height not divisible by 2 (320x427)`

Have you tried passing different width and height (specifically width as it is used in the scale command).

Here is the relevant code on android - 

```
if (maintainAspectRatio) {
    clipOut.videoFilter = "scale=" + outputWidth + ":-1";
} else {
    clipOut.width = outputWidth;
    clipOut.height = outputHeight;
}
```

Please try width = 640 and height = 640 and let me know if the issue is solved.

**Comment by glauconsantana** [comment]
height not divisible by 2 (640x853)

**Comment by rossmartin** [comment]
And just to confirm this is on a real device?  If so which devices?

**Comment by glauconsantana** [comment]
Galaxy Tab A
Galaxy S4 Mini

**Comment by rossmartin** [comment]
Do you know what the default resolution is on the videos recorded on these devices?

**Comment by glauconsantana** [comment]
At log:
D/VideoEditor( 5308): shellOut: Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 640x480, 3115 kb/s, 23.83 fps, 24 tbr, 90k tbn, 180k tbc (default)

**Comment by rossmartin** [comment]
Here is the solution (I should have googled sooner) - http://stackoverflow.com/questions/20847674/ffmpeg-libx264-height-not-divisible-by-2

So, all you need to do in order to fix this is 

`clipOut.videoFilter = "scale=" + outputWidth + ":-2";`

https://github.com/jbavari/cordova-plugin-video-editor/blob/master/src/android/VideoEditor.java#L527

I'm going to go ahead and make this change and publish a new version of the plugin.

**Comment by glauconsantana** [comment]
Excelent. Thank you!

**Comment by rossmartin** [comment]
Thanks for reporting this.  1.0.7 has this fixed and I've published to npm and made a new tag here.

You can fix this in your existing code or uninstall/reinstall the plugin.
