### ISSUE TITLE
Add ffmpeg for ios 

### ISSUE THREAD

**Issue by Shrhawk** [jbavari/cordova-plugin-video-editor#67]
Any plans for adding ffmpeg  for ios ?

**Comment by rossmartin** [comment]
It's not currently planned.  ffmpeg isn't needed on iOS, there are built in mechanisms for video transcoding.  Also, Apple likely won't approve apps that use 3rd party libraries like ffmpeg.

Thanks.

https://github.com/jbavari/cordova-plugin-video-editor/issues/52
