### ISSUE TITLE
Not valid import com.netcompss.loader.LoadJNI;

### ISSUE THREAD

**Issue by mouhammad-zd** [jbavari/cordova-plugin-video-editor#8]
Hello when i add your plugin to my project using this syntax
             cordova plugin add https://github.com/jbavari/cordova-plugin-video-editor.git
And after i build my project a new error is occured which points to this import syntax
            import com.netcompss.loader.LoadJNI;

As i think their is no package with this name or at least my project cannot access this library so what i need to solve this issue ?

Thank in advance for best regards hope this will solved in next hours due the necessity of this plugin in my project :(

**Comment by mouhammad-zd** [comment]
Please can you tell me how to install and setup the plugin correctly may the problem is due an error in setting the plugin up

Did i need anything other than adding the plugin via cordova command line ? Did i need to change or add some configuration ? Did i need to add it from github or i must clone it and add it locally ? Please answer me due an urgent state ! \

Thanks in advance for any regards !

**Comment by rossmartin** [comment]
Sorry for the long delay in a response.  I rewrote the Android version of the plugin using a different ffmpeg android library so this should not be an issue anymore.  I abandoned the original ffmpeg library becuase of licensing and the `android-ffmpeg-java` is better also.
