### ISSUE TITLE
Android Transcode is not working.

### ISSUE THREAD

**Issue by cmboros** [jbavari/cordova-plugin-video-editor#80]
Hey

Im using the plugin on a project and everything is working on iOS but not on android. 
On android the video is not transcode and the success transcode function is not returning anything. If i change the path the error function is trigger but when the path is correct the success is not working. 

Also the thumbnail is created the only thing that is not working is the transcode.

I have try all the configuration possible and nothing i'm using cordova-plugin-media-capture@1.2.0 and cordova-plugin-video-editor@1.0.9 

```
var videoCaptureSuccess = function(mediaFiles) {
    // Wrap this below in a ~100 ms timeout on Android if
    // you just recorded the video using the capture plugin.
    // For some reason it is not available immediately in the file system.

    setTimeout(function(){

      var file = mediaFiles[0].fullPath;
      var videoFileName = Random.id(); // I suggest a uuid

      VideoEditor.transcodeVideo(
        videoTranscodeSuccess,
        videoTranscodeError,
        {
          fileUri: file,
          outputFileName: videoFileName,
          quality: 100,
          outputFileType: VideoEditorOptions.OutputFileType.MPEG4,
          optimizeForNetworkUse: VideoEditorOptions.OptimizeForNetworkUse.YES,
          saveToLibrary: true,
          maintainAspectRatio: true,
          width: 640,
          height: 640,
          videoBitrate: 1000000, // 1 megabit
          audioChannels: 2,
          audioSampleRate: 44100,
          audioBitrate: 128000,
          progress: function(info) {
           console.log('transcodeVideo progress callback, info: ' + info);
         }
        }
      );

      VideoEditor.createThumbnail(
        createThumbnailSuccess,
        createThumbnailError,
        {
          fileUri: file,
          outputFileName: videoFileName,
          atTime: 2, // optional, location in the video to create the thumbnail (in seconds)
          quality: 100 // optional, quality of the thumbnail (between 1 and 100)
        }
      );

    }, 100);
  }
```

```
var videoTranscodeSuccess = function(result) { // is not trigger
    console.log('videoTranscodeSuccess, result: ' + result); 
}
```

```
var videoCaptureError = function(error) { // is trigger if i mess with the path
    navigator.notification.alert('ERROR:' + error.message, null, "Capture Error");
}
```

Thanks in advance for the help.

**Comment by cmboros** [comment]
After i change to save to library i see that the transcoding is working the issue is that i no visual feedback and the success function is not trigger after is done. 

I will like after is done to upload to S3 (is already implemented and working on iOS)

Thnaks

**Comment by rossmartin** [comment]
What android device and version are you using?

What kind of file name is being generated with `Random.id()` ?

Your _anonymous_ callback functions - are they defined above the transcodeVideo call?

**Comment by cmboros** [comment]
Hello,

Android is 4.4.2 and the model is BLU ADVANCE 4.0L i also test it on a LG G5 and it has the same issue. 

Here is all my code: https://gist.github.com/cmboros/857cbfd5d454f6479b8bbd643fc16845

Rnadom.id() is a meteor package https://atmospherejs.com/meteor/random 

Thanks,
Costi

**Comment by AymanFekri** [comment]
+1 
theres no output returned after transcoding

**Comment by cmboros** [comment]
@rossmartin @AymanFekri  i made it to work by removing the thumbnail function position  and generate the thumbnail after the video is transcode in the transcode success function from the video output. 

If i add the position of VideoEditor.transcodeVideo to be second and VideoEditor.createThumbnail to be first  VideoEditor.transcodeVideo is returning the thumbnail if the VideoEditor.createThumbnail is second as position VideoEditor.transcodeVideo is not returning. The way to make it work is by adding VideoEditor.createThumbnail in the VideoEditor.transcodeVideo success callback. Hope my explication is not confusing.

i have create a gist https://gist.github.com/cmboros/7e1efb399aeaac0e7af80151ae8daf0b

Thanks

**Comment by rossmartin** [comment]
🍻  glad to hear you figured it out.  Want me to go ahead and close this issue?

**Comment by cmboros** [comment]
Yes we can close this issue. Thanks for the help.

**Comment by djett41** [comment]
Why is this closed?? Thats great that @cmboros found a workaround, but this is a bug.. transcodeVideo and createThumbnail should be independent and should work regardless of the order.

In a scenario where a user captures a vide, and you need to transcode to ensure playback will work, AND generate a thumbnail, its not a good user experience to have the play button appear, then a second or 2 later the thumbnail (poster) show.
