### ISSUE TITLE
Android createThumbnail atTime is not in seconds, getFrameAt method uses microseconds

### ISSUE THREAD

**Issue by kmturley** [jbavari/cordova-plugin-video-editor#81]
In your comments you have the line:

     atTime         - location in the video to create the thumbnail (in seconds)

https://github.com/jbavari/cordova-plugin-video-editor/blob/master/src/android/VideoEditor.java#L266

However MediaMetadataRetriever's getFrameAt method uses microseconds:
http://stackoverflow.com/a/13592700/798160

When using this feature I have been multiplying:

     atTime: 2 * 1000000, // 2 seconds
     fileUri: 'file:///storage/emulated/0/Movies/outro.mp4',
     outputFileName: 'test'

I'd imagine you will need to adjust either the documentation or the function!

**Comment by rossmartin** [comment]
Thanks I'll update the source code tomorrow.
