### ISSUE TITLE
Update Typings

### ISSUE THREAD

**Issue by aksharpatel47** [jbavari/cordova-plugin-video-editor#83]
I'm trying to use this plugin with ionic 2 and typescript. I noticed that the typings are not up to date with current version of the library. I'm updating them as I use the plugin. This is my first time writing typings for a cordova plugin. Any information would be appreciated.

**Comment by rossmartin** [comment]
I can update the typings this weekend, I've kinda neglected it lately.  I have been using typescript lately but none of the projects of mine that use this plugin are typescript (yet).

A pull request is welcome too.
