### ISSUE TITLE
videoTranscodeError Error 0xfffffc0e codec

### ISSUE THREAD

**Issue by tsukasa1989** [jbavari/cordova-plugin-video-editor#90]
Hello,

I've only tried the demo, but as mentioned I put a timeout of 100ms after capture.captureVideo and before the transcodeVideo. The file.fullPath has a valid value but I get a codec error, which I don't know how to resolve. The error code I get is: 

    android.media.MediaCodec$CodecException: Error 0xfffffc0e

If I Google it, mostly I get a configuration error. I'm using a Sony Xperia M4 Aqua with Android 5.

Thanks,

Niels

**Comment by lsilvs** [comment]
I'm getting the same error.
Works fine for iOS but for Android it fails.
It seems to be related to the video dimensions because if I omit the options "height" and "width" it works.
Any joy with that?

**Comment by lsilvs** [comment]
Updating the plugin solved my issue.

https://github.com/jbavari/cordova-plugin-video-editor/releases/tag/1.1.1

Best,

**Comment by lsilvs** [comment]
I've figured out that updating the plugin to 1.1.1 fixed the issue only for videos with 4:3 ratio.
16:9 videos are still getting the android.media.MediaCodec$CodecException.

To solve that, I've forked the repo and made some changes on CustomAndroidFormatStrategy.java file.

See the forked repo here: [https://github.com/lsilvs/cordova-plugin-video-editor](https://github.com/lsilvs/cordova-plugin-video-editor)

@rossmartin Let me know if you want to incorporate my changes to the official repo.

I hope it can help someone else.

**Comment by rossmartin** [comment]
Thanks I don't currently have time to integrate changes so a pull request is ideal.  It sounds like PR https://github.com/jbavari/cordova-plugin-video-editor/pull/89 is what broke the 16:9 videos.

**Comment by jaz303** [comment]
I think height needs to be a multiple of 2. I worked around this issue by calculating width/height manually then rounding height up if necessary.

**Comment by scopsy** [comment]
When there will be a new version release including this fix ?

**Comment by rossmartin** [comment]
@scopsy I forgot to increment the plugin version and publish to npm.  This is done and its tagged at [1.1.2](https://github.com/jbavari/cordova-plugin-video-editor/tree/1.1.2)

**Comment by scopsy** [comment]
@rossmartin Still getting this with version 1.1.2 on android 6.0, any suggestions ?
android.media.MediaCodec$CodecException: Error 0xfffffc0e

**Comment by dheerajchugh303** [comment]
I am also getting the same error on 5.1.1 version and handset in mi note 3

**Comment by dheerajchugh303** [comment]
If we set the width and height in options then this issue wont come.

**Comment by lsilvs** [comment]
I haven't had a chance to look into that yet but it should be just the case of setting the width and height as the original values when it is not defined.
I'll have a look as soon as I can.

**Comment by Redmage3555** [comment]
Can this be reopened? I have experienced this problem recently, it still exists.

**Comment by lsilvs** [comment]
I've created a [PR](https://github.com/jbavari/cordova-plugin-video-editor/pull/114) that I reckon will handle that.

It's now using the input file width/height if the output width/height is not given.

Can anyone check if it fixes the issue?

**Comment by akash-pal** [comment]
Is this issue fixed? Still facing same issue on redmi not 3

**Comment by EternallLight** [comment]
Is this issue fixed? Still facing the same issue on Zuk Z1 (Android 5.1)

**Comment by vgokul129** [comment]
In my case i have configured 0 as width and height. Solved by configuring the exact width and height values. 
`final MediaFormat format = MediaFormat.createVideoFormat(MIME_TYPE, 640, 480);`

**Comment by nagesh1044** [comment]
In my case i have 1200  width and 1920 height.
final MediaFormat format = MediaFormat.createVideoFormat(MIME_TYPE, 1200  , 1920 );
 i am getting below exception .
    android.media.MediaCodec$CodecException: Error 0xfffffc0e

How to solve this problem?

**Comment by xiongshiming** [comment]
when i used the plugin cordova-plugin-video-editor ,it cameout error: JSON error,how should i resolve it ,thanks
