### ISSUE TITLE
[Android] Trim video

### ISSUE THREAD

**Issue by Xwalk-Company** [jbavari/cordova-plugin-video-editor#98]
Hi,
In the continuation of topic on the withdrawal of ffmpeg for performance on android, would it be possible to trim videos on android without ffmpeg? 

If so, what would be the steps to follow?

We want to help, as you made the comparison with VINE, it is really important to get on speed for upload file.

**Comment by Hesesses** [comment]
Trim for android 👍

**Comment by Xwalk-Company** [comment]
Same for me
